### ISSUE TITLE
UltraViolet Node not starting

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [titaniumnetwork-dev/Ultraviolet#10]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior
Start up a website and run

## Current Behavior
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@tomphttp/bare-server-node' imported from /home/runner/Ultraviolet-Node/src/index.js`

## Possible Solution
Not sure

## Steps to Reproduce

1. 
2.
3.
4.

**Comment by Abnumality** [comment]
so like do you have the package installed???

**Comment by BubblePlayzTHEREAL** [comment]
> so like do you have the package installed???

How do I install it?

**Comment by BubblePlayzTHEREAL** [comment]
Nevermind. I found it out

**Comment by genericness** [comment]
run `npm install`
