### ISSUE TITLE
When opening through Koyeb, the application says error. It has worked up until today. don't know why it stopped.

### ISSUE THREAD

**Issue by FailSafe17** [titaniumnetwork-dev/Ultraviolet#100]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by FailSafe17** [comment]
Layman's terms

**Comment by tuta-amb** [comment]
@FailSafe17 Not really that complicated. Go to your Koyeb deployment and view the logs. Since you didn't provide any additional information (not even _what_ error!), we can't help you any further.

**Comment by FailSafe17** [comment]
It's hard to describe. Sorry for the inconsistency. Here are some shots of the problem on y end.

![Screenshot 2024-01-17 3 53 49 PM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/148401601/2ec15022-fd01-40e4-8139-8f46e32ff4a6)
![Screenshot 2024-01-17 3 53 57 PM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/148401601/8279d7dc-3ef9-41e1-a05a-a86cd0b8d13e)
![Screenshot 2024-01-17 3 54 09 PM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/148401601/55688bdd-91e5-4e7f-80bd-683db6337868)

**Comment by tuta-amb** [comment]
@FailSafe17 Definitely looks like the bare server is down. Try sending logs. Have you tried restarting the (bare) server?

**Comment by FailSafe17** [comment]
@tuta-amb I've tried and nothing seems to happen

**Comment by FailSafe17** [comment]
@tuta-amb How would one go about that?

**Comment by tuta-amb** [comment]
Sending logs? Haven't used Koyeb at all, but there should be a logs page somewhere. If you can't find it, google it.

For restarting the bare server, if you operate the server then try redeploying it. Otherwise you should try to contact the server owner.

**Comment by Riftriot** [comment]
This is not an issue with UV
