### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by SchoolTARMaster** [titaniumnetwork-dev/Ultraviolet#101]
###  How to use ?
So, I created a github codespace on a blank repo, and ran the following commands:
`git clone https://github.com/titaniumnetwork-dev/Ultraviolet.git`
`cd Ultraviolet`
`npm install`
`npm run build`
I looked at the wiki to find these commands, and after running them, I didn't understand what the wiki meant to do with the big node.js code (can be found at <a>https://github.com/titaniumnetwork-dev/Ultraviolet/wiki/Installing</a>). Where do I put it, and how to use it (path for putting it can be useful) ? And I don't need the frontend for now, because I already know where it is.

**Comment by tuta-amb** [comment]
bro you are stupid

this is not an app for production
like you can't run it

you need [ultraviolet app](https://github.com/titaniumnetwork-dev/Ultraviolet-App) for that

**Comment by SchoolTARMaster** [comment]
Well thanks but I'm not stupid like you 😂😂😂😂😂😂🤣🤣🤣🤣🤣🤣

**Comment by IncognitoTGT** [comment]
average skid:

**Comment by tuta-amb** [comment]
> 😂😂🤣🤣🤣🤣🤣🤣

?????
fucking skid

doesn't even know how to run a script

**Comment by SchoolTARMaster** [comment]
bro I did deploy a different version of UV before
i'm not dumb

**Comment by tuta-amb** [comment]
> bro I did deploy a different version of UV before
> i'm not dumb

says the one who can't figure out how to run a nodejs server WITH prewritten code
definitely a skid, tech illiterate
only thing that you can do is run copy pasted terminal commands

----

you do understand that this ISN'T a way to run an ultraviolet proxy. you CANNOT run an ultraviolet instance using just this repo.

**Comment by IncognitoTGT** [comment]
Check his repos that he has, definitely a skid.

**Comment by SchoolTARMaster** [comment]
> > bro I did deploy a different version of UV before
> > i'm not dumb
> 
> says the one who can't figure out how to run a nodejs server WITH prewritten code definitely a skid, tech illiterate only thing that you can do is run copy pasted terminal commands
> 
> you do understand that this ISN'T a way to run an ultraviolet proxy. you CANNOT run an ultraviolet instance using just this repo.

I UNDERSTAND NOW GET OUTTA HERE

**Comment by tuta-amb** [comment]
> > > bro I did deploy a different version of UV before
> > > i'm not dumb
> > 
> > 
> > says the one who can't figure out how to run a nodejs server WITH prewritten code definitely a skid, tech illiterate only thing that you can do is run copy pasted terminal commands
> > you do understand that this ISN'T a way to run an ultraviolet proxy. you CANNOT run an ultraviolet instance using just this repo.
> 
> I UNDERSTAND NOW GET OUTTA HERE

so why are you trying to do so then?

dumb skids make me angy

**Comment by tuta-amb** [comment]
@VillainsRule don't really think that he's harassing, literally just said that he was a skid tbh

**Comment by zkayns** [comment]
> > > bro I did deploy a different version of UV before
> > > i'm not dumb
> > 
> > 
> > says the one who can't figure out how to run a nodejs server WITH prewritten code definitely a skid, tech illiterate only thing that you can do is run copy pasted terminal commands
> > you do understand that this ISN'T a way to run an ultraviolet proxy. you CANNOT run an ultraviolet instance using just this repo.
> 
> I UNDERSTAND NOW GET OUTTA HERE
https://github.com/titaniumnetwork-dev/Ultraviolet/pull/82
