### ISSUE TITLE
Retrogames.cc doesn't work 

### ISSUE THREAD

**Issue by 1754Bq** [titaniumnetwork-dev/Ultraviolet#102]
Everytime I go to the site https://retrogames.cc and I press the "Play Game" button. Instead of launching the game, it instead makes an embedded version of itself inside the window. ![Screenshot 2024-01-19 12 59 09 PM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/157149443/81e7ead7-c3a5-4f65-bdda-cb32320870d6) I think a reason why this happens is because they include embed code with where emulatorjs is supposed to be. For a possible solution, I think it could treat the embedded code differently so it can actually work.

**Comment by rxfe-a** [comment]
its the way the website works. not really a UV issue

**Comment by 1754Bq** [comment]
> its the way the website works. not really a UV issue

Well, it works perfectly normal without UV. Is it not a compatibility issue? I've seen other proxies have it work fine. Only specifically UV

**Comment by 1754Bq** [comment]
> Contact RetroGames developers and have them create an issue if they truly believe there is an issue with the software. It is likely a configuration error or modified build on their part.

They have social media accounts, but they don't seem active.

**Comment by 1754Bq** [comment]
Nevermind, I found that rammerhead could handle the site just fine.
