### ISSUE TITLE
2 Bugs

### ISSUE THREAD

**Issue by SchoolTARMaster** [titaniumnetwork-dev/Ultraviolet#103]
### 2 Bugs
Here's what I did so far
I created an empty github codespace, and ran the command to clone this. Then I cloned [Ultraviolet-Static](https://github.com/titaniumnetwork-dev/Ultraviolet-Static/).
Then, I ran:
`cd Ultraviolet`
`npm install`
`npm run build`
Then, I copied everything in the `dist` folder to the `uv` folder in `public` in `Ultraviolet-Static`, excluding `uv.config.js`, any `.map` files, and the `uv.bundle.js.LICENSE.txt` file. I tweaked `uv.config.js`a bit, then I then went to the `package.json` file to add a start script and install `express` and `bare server 2.0.1` as normal dependencies. I installed dependencies, created the `index.js` file from the <a href="https://github.com/titaniumnetwork-dev/Ultraviolet/wiki/Installing">wiki</a>, and tweaked it. I ran it, made the port visibility public, and opened it in my browser. The proxy works, but there are two bugs:
1: When I go to google.com, search for something, and hit enter, it acts like I need to write another line.
2: When I look at the "People also ask" part of a search result, clicking any of them does not do anything.
Anybody has a fix other than clicking Google Search?

**Comment by SchoolTARMaster** [comment]
Anybody responding ?

**Comment by tuta-amb** [comment]
not a bug, skill issue

**Comment by IncognitoTGT** [comment]
use https://github.com/titaniumnetwork-dev/ultraviolet-app

**Comment by SchoolTARMaster** [comment]
I mean how do websites load but enter and People Also Ask don’t work ?

**Comment by tuta-amb** [comment]
some scripts aren't loading thats what
just use ultraviolet-app if you're not deploying a custom proxy lol

**Comment by SchoolTARMaster** [comment]
> some scripts aren't loading thats what just use ultraviolet-app if you're not deploying a custom proxy lol

1: I don't want to be lazy to use Ultraviolet-App
2: Then how do you make the scripts load ?

**Comment by tuta-amb** [comment]
> 1: I don't want to be lazy to use Ultraviolet-App

You're not. It's literally the recommended way. This is like instead of buying a car, saying "oh I don't want to be lazy, so I'm going to assemble the car parts myself".

> 2: Then how do you make the scripts load ?

No idea. I don't really know anything about your setup, and I don't care much for it. Just use `ultraviolet-app` like everyone else and it'll be all good.

**Comment by AverageJuliet** [comment]
ultraviolet-app is goated

**Comment by tuta-amb** [comment]
@AverageJuliet wouldn't say that, it's decent ig

**Comment by tuta-amb** [comment]
@VillainsRule Is the SW registering not done client side in `ultraviolet-static`?

**Comment by SchoolTARMaster** [comment]
I have both sw.js AND uv.sw.js in the uv folder of public in Ultraviolet-Static

**Comment by proudparrot2** [comment]
It’s a UV bug plain and simple. Fix it yourself if you must, or use a different search engine.

**Comment by tuta-amb** [comment]
> > @VillainsRule Is the SW registering not done client side in `ultraviolet-static`?
> 
> They are one and the same thing in my mind.

huh what

**Comment by SchoolTARMaster** [comment]
I think I should just add Ultraviolet as a dependency instead of a peer dependency.

**Comment by SchoolTARMaster** [comment]
> Scripts are loaded by registering service workers, which can be seen in `ultraviolet-app`. This is not an issue, please close this.

I got SW errors, but when I moved `sw.js` to the `uv` directory, sites load, but scripts don't.
