### ISSUE TITLE
UI Bug on Website

### ISSUE THREAD

**Issue by TartejBrothers** [titaniumnetwork-dev/Ultraviolet#104]
- The search bar is getting overlayed by header text in mobile view
- [Link To Page](https://docs.titaniumnetwork.org/guides/nginx/)

## Current Behavior
- Default
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/112921727/58793664-553f-45f7-8fbd-6b6c52b1dce5)

- When search is clicked
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/112921727/f803ffed-63ba-41fc-b0ea-1b6dffe74ce2)

## Possible Solution

- Move the search bar to the menu 

## Steps to Reproduce

1. [Open this link](https://docs.titaniumnetwork.org/guides/nginx/)
2. Turn on Mobile View

**Comment by proudparrot2** [comment]
1. That is relating to the Titanium Network docs which can be found [here](https://github.com/titaniumnetwork-dev/Oxide-Docs/tree/master)
2. TN docs uses Docusaurus, so they don’t have control over the formatting of that search bar

**Comment by Percslol** [comment]
This is an issue that should be opened up at the Titanium Network docs and not UltraViolet.

closing this as wont fix
