### ISSUE TITLE
Discord invite valid, PLS HELP ME

### ISSUE THREAD

**Issue by pretzer25** [titaniumnetwork-dev/Ultraviolet#107]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

So firstly, Discord invite expired, so I couldn't post there, secondly, can anyone tell me how the encoding and decoding work for the url, it would be really useful for my project as it requires it.

## Expected Behavior

that i should know it

## Current Behavior

I don't know it

## Possible Solution

tell me how it does the encoding/decoding

## Steps to Reproduce

1.use the proxy
2.look at the link using your eyes
3. anilize that it is not the same thing as the original link
4.no

## Context (Environment)

project

project

i already told you

## Detailed Description

no

## Possible Implementation

no

**Comment by proudparrot2** [comment]
discord invite is [discord.gg/unblock](https://discord.gg/unblock)

encoding function can be found [here](https://github.com/titaniumnetwork-dev/Ultraviolet/blob/main/src/rewrite/codecs.js). ultraviolet uses them to encode and decode urls.

**Comment by tuta-amb** [comment]
i've made a simple site for myself to en/decode the urls, it's here: [ultraviolet-decoder.pages.dev](https://ultraviolet-decoder.pages.dev/)

**Comment by pretzer25** [comment]
thx
