### ISSUE TITLE
Security leak with localhost and LAN address

### ISSUE THREAD

**Issue by ruochenjia** [titaniumnetwork-dev/Ultraviolet#11]
Users can access `127.0.0.1` and `10.0.0.0/8` which means they can access server internal without any restrictions.

**Comment by desplmfao** [comment]
then make a blacklist in bare

**Comment by e9x** [comment]
Coming soon.. https://github.com/tomphttp/bare-server-node/commit/1ec1e3c8679444d6c6230b9b95299ee3df1d32e7
