### ISSUE TITLE
Application Error.

### ISSUE THREAD

**Issue by RedLazarbeam2** [titaniumnetwork-dev/Ultraviolet#110]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

The proxy I use with ultraviolet, [](https://developmentbuild.herokuapp.com/) does not properly work most of the time. At random times of day it will start working, but only for about a half-hour at a time.

## Expected Behavior

Proxy opens and allows me to enter links.

## Current Behavior

Proxy loads for ~1 minute and gives me this error:
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

## Steps to Reproduce

1. Open up the proxy
2.
3.
4.

## Context (Environment)

It will not even allow me to access the UV ui.

**Comment by RedLazarbeam2** [comment]
Proxy is at https://developmentbuild.herokuapp.com/

**Comment by tuta-amb** [comment]
that's not an ultraviolet problem, that's whoever is running the proxy's fault

u gotta contact them

**Comment by RedLazarbeam2** [comment]
Alright. How would I get a better proxy? I don't exactly have a ton of coding knowledge.
