### ISSUE TITLE
__uv is not defined error

### ISSUE THREAD

**Issue by not-amplify** [titaniumnetwork-dev/Ultraviolet#111]
HI, In my proxy im getting __uv is not defined errors in inspect and ive literally been attemting to fix this for a few weeks now, if yall could help out this would be awesome.

**Comment by Rac3trase** [comment]
I am getting the same issue! Did you ever get to fixing this? And if so how would I?

**Comment by proudparrot2** [comment]
Make sure the file paths in the config are absolute and valid
