### ISSUE TITLE
is there a way to use the ultraviolet files in a iframe?

### ISSUE THREAD

**Issue by pretzer25** [titaniumnetwork-dev/Ultraviolet#112]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

i want to iframe my site like "<iframe src="./service/SOMETHING" but the ultraviolet files wont go through an iframe in newer chrome versions

## Possible Solution

tell me how to add the files to the iframe automatically

## Steps to Reproduce

1.
2.
3.
4.

**Comment by IncognitoTGT** [comment]
skid moment

**Comment by rxfe-a** [comment]
register the sw

**Comment by pretzer25** [comment]
> register the sw

can you help me?`<style>
          #ifra {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            border: none;
        }
</style>

<script src="/uv/uv.bundle.js"></script>
<script src="/uv/uv.config.js"></script>
<script src="/register-sw.js"></script>

<iframe id="ifra" src="./service/hvtrs8%2F-nmw%2Cge%2Fcprs-nknha%2Fkkwk%2F35%3A6-bnomnq-vd%2F6%2Chvmn"></iframe>`

**Comment by IncognitoTGT** [comment]
skidding interstellar goes HARD

**Comment by xbubbo** [comment]
> > register the sw
> 
> can you help me? `
> 
> <style> #ifra { position: fixed; top: 0; left: 0; width: 100%; height: 100%; border: none; } </style> <script src="/uv/uv.bundle.js"></script> <script src="/uv/uv.config.js"></script> <script src="/register-sw.js"></script> <iframe id="ifra" src="./service/hvtrs8%2F-nmw%2Cge%2Fcprs-nknha%2Fkkwk%2F35%3A6-bnomnq-vd%2F6%2Chvmn"></iframe> `

skiddy skid

**Comment by pretzer25** [comment]
I NEED HELP!!!!!!!!!!

**Comment by rxfe-a** [comment]
> I NEED HELP!!!!!!!!!!

smartest interstellar user

```
navigator.serviceWorker.register('/uv/sw.js', {
    scope: __uv$config.prefix,
  });
```

**Comment by proudparrot2** [comment]
After registering the service worker as above, you can set the iframe's src attribute to
```
/service/<encoded url>
```
You can encode a URL by doing `__uv$config.encodeUrl('https://example.com')` or replace with your url (must be an actual url)

**Comment by proudparrot2** [comment]
I don't know what that is

**Comment by rxfe-a** [comment]
> it doesn't work
> 
> <style> #iframe { position: fixed; top: 0; left: 0; width: 100%; height: 100%; border: none; } </style> <iframe class="iframe" id="iframe"></iframe> <script src="/uv/uv.bundle.js"></script> <script src="/uv/uv.config.js"></script> <script src="/register-sw.js"></script> <script src="/search.js"></script> <script> navigator.serviceWorker.register('../sw.js', { scope: __uv$config.prefix, }); iframe.src="/service/hvtrs8%2F-nmw%2Cge%2Frlcy-rmbnoz-aoppmrctkol%2F7369-rmbnoz"; </script>

This should work?
The reason it didn't work is because the 'iframe' variable does not exist atleast to my knowledge,
If it doesn't work please send the output in the console.

```html
<style>
  #iframe {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border: none;
  }
</style> <iframe class="iframe" id="iframe"></iframe>
<script src="/uv/uv.bundle.js"></script>
<script src="/uv/uv.config.js"></script>
<script src="/register-sw.js"></script>
<script src="/search.js"></script>
<script>
  navigator.serviceWorker.register('../sw.js', {
    scope: __uv$config.prefix,
  });
  document.getElementById('iframe').src = "/service/hvtrs8%2F-nmw%2Cge%2Frlcy-rmbnoz-aoppmrctkol%2F7369-rmbnoz";
</script>
```

**Comment by pretzer25** [comment]
> > it doesn't work
> > <style> #iframe { position: fixed; top: 0; left: 0; width: 100%; height: 100%; border: none; } </style> <iframe class="iframe" id="iframe"></iframe> <script src="/uv/uv.bundle.js"></script> <script src="/uv/uv.config.js"></script> <script src="/register-sw.js"></script> <script src="/search.js"></script> <script> navigator.serviceWorker.register('../sw.js', { scope: __uv$config.prefix, }); iframe.src="/service/hvtrs8%2F-nmw%2Cge%2Frlcy-rmbnoz-aoppmrctkol%2F7369-rmbnoz"; </script>
> 
> This _solution_ should work? The reason it didn't work is because the 'iframe' variable does not exist atleast to my knowledge, If it doesn't work please send the output in the console.
> 
> ```
> <style>
>   #iframe {
>     position: fixed;
>     top: 0;
>     left: 0;
>     width: 100%;
>     height: 100%;
>     border: none;
>   }
> </style> <iframe class="iframe" id="iframe"></iframe>
> <script src="/uv/uv.bundle.js"></script>
> <script src="/uv/uv.config.js"></script>
> <script src="/register-sw.js"></script>
> <script src="/search.js"></script>
> <script>
>   navigator.serviceWorker.register('../sw.js', {
>     scope: __uv$config.prefix,
>   });
>   document.getElementById('iframe').src = "/service/hvtrs8%2F-nmw%2Cge%2Frlcy-rmbnoz-aoppmrctkol%2F7369-rmbnoz";
> </script>
> ```
it still got 404, the error i get is
GET https://ultra-learn.vercel.app/service/hvtrs8%2F-nmw%2Cge%2Frlcy-rmbnoz-aoppmrctkol%2F7369-rmbnoz 404 (Not Found)

**Comment by IncognitoTGT** [comment]
skid

**Comment by rxfe-a** [comment]
> > > it doesn't work
> > > <style> #iframe { position: fixed; top: 0; left: 0; width: 100%; height: 100%; border: none; } </style> <iframe class="iframe" id="iframe"></iframe> <script src="/uv/uv.bundle.js"></script> <script src="/uv/uv.config.js"></script> <script src="/register-sw.js"></script> <script src="/search.js"></script> <script> navigator.serviceWorker.register('../sw.js', { scope: __uv$config.prefix, }); iframe.src="/service/hvtrs8%2F-nmw%2Cge%2Frlcy-rmbnoz-aoppmrctkol%2F7369-rmbnoz"; </script>
> > 
> > 
> > This _solution_ should work? The reason it didn't work is because the 'iframe' variable does not exist atleast to my knowledge, If it doesn't work please send the output in the console.
> > ```
> > <style>
> >   #iframe {
> >     position: fixed;
> >     top: 0;
> >     left: 0;
> >     width: 100%;
> >     height: 100%;
> >     border: none;
> >   }
> > </style> <iframe class="iframe" id="iframe"></iframe>
> > <script src="/uv/uv.bundle.js"></script>
> > <script src="/uv/uv.config.js"></script>
> > <script src="/register-sw.js"></script>
> > <script src="/search.js"></script>
> > <script>
> >   navigator.serviceWorker.register('../sw.js', {
> >     scope: __uv$config.prefix,
> >   });
> >   document.getElementById('iframe').src = "/service/hvtrs8%2F-nmw%2Cge%2Frlcy-rmbnoz-aoppmrctkol%2F7369-rmbnoz";
> > </script>
> > ```
> 
> it still got 404, the error i get is GET https://ultra-learn.vercel.app/service/hvtrs8%2F-nmw%2Cge%2Frlcy-rmbnoz-aoppmrctkol%2F7369-rmbnoz 404 (Not Found)


smartass

Look heres a example
on how to UV

```html

<!DOCTYPE html>
<head>
    <title>[]</title>
    <style>
        body {
            background: transparent;
            margin: 0;
            padding: 0;
            height: 100vh;
            width: 100%;
            display: flex;
        }

        iframe {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            border: none;
        }
    </style>
    <script src="uv/uv.bundle.js"></script>
    <script src="uv/uv.config.js"></script>
</head>
<body>
    <script>
        const yourshittyfuckingurl = 'https://now.gg/play/roblox-corporation/5349/roblox'; // typical 9 year old
        navigator.serviceWorker.register('register-sw.js', {
            scope: __uv$config.prefix,
        });

        const skid = document.createElement('iframe'); // should be you but whatever
        document.body.appendChild(skid);

        skid.src = __uv$config.prefix + __uv$config.encodeUrl(yourshittyfuckingurl);
    </script>
</body>
</html>

```


Or you can do this

```html

<!DOCTYPE html>
<head>
    <title>[]</title>
    <style>
        body {
            background: transparent;
            margin: 0;
            padding: 0;
            height: 100vh;
            width: 100%;
            display: flex;
        }

        iframe {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            border: none;
        }
    </style>
    <script src="uv/uv.bundle.js"></script>
    <script src="uv/uv.config.js"></script>
</head>
<body>
    <script>
        const yourshittyfuckingurl = '/service/hvtrs8%2F-nmw%2Cge%2Frlcy-rmbnoz-aoppmrctkol%2F7369-rmbnoz'; // typical 9 year old
        navigator.serviceWorker.register('register-sw.js', {
            scope: __uv$config.prefix,
        });

        const skid = document.createElement('iframe'); // should be you but whatever
        document.body.appendChild(skid);

        skid.src = yourshittyfuckingurl
    </script>
</body>
</html>
```

Your UV Config must also work according to the URL in order to use the last example

**Comment by pretzer25** [comment]
bro do you think im stupid, i tried everything, even that, nothing works, i made sure everything is right, even asked ai for help, i even checked the console ten times for errors, ITS THE SAME, 404, but i just decided to give up, so im closing

**Comment by IncognitoTGT** [comment]
skiddy skid

**Comment by rxfe-a** [comment]
> bro do you think im stupid, i tried everything, even that, nothing works, i made sure everything is right, even asked ai for help, i even checked the console ten times for errors, ITS THE SAME, 404, but i just decided to give up, so im closing

<img src="https://github.com/titaniumnetwork-dev/Ultraviolet/assets/104333985/601fbff4-632d-4cce-b5df-2fdcb7c2d976" width= 400px height=400px>

vercel error
