### ISSUE TITLE
Bare Server

### ISSUE THREAD

**Issue by sankuhubreal** [titaniumnetwork-dev/Ultraviolet#113]
When trying to search with a **clean** version of Ultraviolet, I am receiving an error of "there are no bare clients" with "Code: UNKOWN". Here's a screenshot of my issue. Any way to resolve it? Thanks!
![error](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/156705849/730b2653-a5f7-4643-a9a2-21c3ab70eee0)

**Comment by whos-evan** [comment]
I also get this same issue. No idea how to fix it.

**Comment by tuta-amb** [comment]
setup issue, no bare server being hosted probably

**Comment by not-amplify** [comment]
> setup issue, no bare server being hosted probably

I had this same issue and my bare was intact it appears to be an issue with Ultraviolet.

**Comment by not-amplify** [comment]
> > setup issue, no bare server being hosted probably
> 
> I had this same issue and my bare was intact it appears to be an issue with Ultraviolet.

I specifically found that when compiled this error has to do with uv.sw.js

**Comment by tuta-amb** [comment]
maybe more sw registering problems

**Comment by not-amplify** [comment]
> maybe more sw registering problems

That’s what I thought so I tried setting my register method to the default, my own, and few others. None of them worked

**Comment by NottPeak** [comment]
What service is this being hosted on?

**Comment by not-amplify** [comment]
> What service is this being hosted on?

I’ve used every hosting I can think of all the same…

**Comment by NottPeak** [comment]
its something with your implementation then, i would recommend looking at [Ultraviolet App](https://github.com/titaniumnetwork-dev/ultraviolet-app) or other sites like nebula for an example. you could also leave a link to a repo with your current code and ill check it out

**Comment by zptqghsw** [comment]
> 那么它与你的实现有关，我建议你看看 [Ultraviolet App](https://github.com/titaniumnetwork-dev/ultraviolet-app) 或其他网站，如 nebula 作为例子。你也可以留下一个带有你当前代码的存储库的链接，然后检查一下

nebula  are also similar issues！

**Comment by zptqghsw** [comment]
> its something with your implementation then, i would recommend looking at [Ultraviolet App](https://github.com/titaniumnetwork-dev/ultraviolet-app) or other sites like nebula for an example. you could also leave a link to a repo with your current code and ill check it out

nebula has also similar issues！

**Comment by ProgrammerIn-wonderland** [comment]
Known issue with new version of Ultraviolet, you can use an older version for now

**Comment by not-amplify** [comment]
> Known issue with new version of Ultraviolet, you can use an older version for now

I got it working... people are not applying epoxy correctly. people need to add ```importScripts("/epoxy/index.js);``` and add the the Baremux set transport method to the epoxy and configure the wispUrl and then your set.

**Comment by not-amplify** [comment]
> > > Known issue with new version of Ultraviolet, you can use an older version for now
> > 
> > 
> > I got it working... people are not applying epoxy correctly. people need to add `importScripts("/epoxy/index.js);` and add the the Baremux set transport method to the epoxy and configure the wispUrl and then your set.
> 
> How to do it, can you give a tutorial?

I'm currently working on getting it to use libcurl to see which is better cause I'm still having some issues where wisp will crash with epoxy

**Comment by not-amplify** [comment]
> > > > Known issue with new version of Ultraviolet, you can use an older version for now
> > > 
> > > 
> > > I got it working... people are not applying epoxy correctly. people need to add `importScripts("/epoxy/index.js);` and add the the Baremux set transport method to the epoxy and configure the wispUrl and then your set.
> > 
> > 
> > How to do it, can you give a tutorial?
> 
> I'm currently working on getting it to use libcurl to see which is better cause I'm still having some issues where wisp will crash with epoxy

does anybody know how to successfully implete=ment libcurl with the backend?

**Comment by Percslol** [comment]
this issue was resolved in 3.1.1, try updating uv-app if you are using it or updating your uv version if its your own custom frontend

closing as completed
