### ISSUE TITLE
Taming.io Fix PLease

### ISSUE THREAD

**Issue by Blapizy** [titaniumnetwork-dev/Ultraviolet#116]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by forvirtualmachine** [comment]
Nope its not

**Comment by forvirtualmachine** [comment]
nvm it is!

**Comment by proudparrot2** [comment]
Average ultraviolet maintainer
