### ISSUE TITLE
Taming io Fix Please.

### ISSUE THREAD

**Issue by Blapizy** [titaniumnetwork-dev/Ultraviolet#117]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

Taming io does not work in ultraviolet proxies

## Expected Behavior

When you click on it it should load and let u interact etc.

## Current Behavior

The basic screen loads and it then freezes

## Possible Solution

Idk how u fix it but many told me its ultraviolet issue so i am asking here.

## Steps to Reproduce

Taming.io

1.
2.
3.
4.

## Context (Environment)

PLay taming.io
<

 Taming.io game not working.

## Detailed Description

fix it so taming.io works.

**Comment by tuta-amb** [comment]
stop u already posted this

**Comment by tuta-amb** [comment]
why'd u close it

**Comment by Riftriot** [comment]
Closed as stale
