### ISSUE TITLE
hdtoday.tv

### ISSUE THREAD

**Issue by ObjectAscended** [titaniumnetwork-dev/Ultraviolet#12]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

hdtoday.tv has a javascript error when trying to watch something
## Expected Behavior

it loads the page
## Current Behavior

This page contains the following errors:
error on line 43 at column 15: Specification mandates value for attribute async
Below is a rendering of the page up to the first error.
## Steps to Reproduce

1. https://hdtoday.tv
2. search for any tv show
3. click on play and choose episode
4. error/bug

## Context (Environment)

trying to watch some tv on restricted network, hosting on github

**Comment by e9x** [comment]
Will not fix.
