### ISSUE TITLE
Now.gg Roblox Not working

### ISSUE THREAD

**Issue by Hydroacid5429** [titaniumnetwork-dev/Ultraviolet#120]
When I try to use now.gg Roblox it gives me a error about some node or now.gg just shows me a message that says "Unsafe Proxy Detected," and it also sometimes just doesn't load the game when it doesn't show the message.

**Comment by proudparrot2** [comment]
Yes, this is something now.gg added and is not an issue with Ultraviolet. It is not an "unsafe proxy," it is them saying "hey you're running a proxy that we don't like, come onto our official domains!"

**Comment by ProgrammerIn-wonderland** [comment]
We can't fix this, 
\- at least, not in the long run 

They are deliberately trying to detect UV, this will turn into a cat and mouse game that's just not worth chasing. If you want to complain, you should complain to now.gg

**Comment by pretzer25** [comment]
YOU CAN FIX THIS, all you need to do is go on ultra-learn.vercel.app i made the app to bypass the proxy detection by reloading until it cant detect now gg warning you, which takes about 1-3 minutes

**Comment by Notplayingallday383** [comment]
> YOU CAN FIX THIS, all you need to do is bypass the proxy detection by reloading until it cant detect now gg warning you, which takes about 1-3 minutes

Your behaving extreamly entitled, If you know how to fix it than do it yourself. This is not a problem with Ultraviolet at all also this is litterally just nowgg being nowgg.

**Comment by yu6x** [comment]
> YOU CAN FIX THIS, all you need to do is bypass the proxy detection by reloading until it cant detect now gg warning you, which takes about 1-3 minutes

it seems like you know the issue so why don't you fix it?

**Comment by 1coolmatt8083** [comment]
they dont care about their costomers and they dont care
THEY JUST DONT CARE!!

**Comment by 1coolmatt8083** [comment]
i mean why would they care they are just plain stupid

**Comment by Percslol** [comment]
this issue has already been stated that it wont be fixed

closing as not planned

**Comment by 1coolmatt8083** [comment]
ya well it should be because now people wont be going to yer site any more

**Comment by 1coolmatt8083** [comment]
plz just FIX THIS

**Comment by kxtzownsu** [comment]
roblox (s)kid calm down, just do your schoolwork and play roblox at home

**Comment by 1coolmatt8083** [comment]
u shouldent be talkin shark hat man

**Comment by proudparrot2** [comment]
This is not an issue with Ultraviolet. We are not “losing customers.” I don’t know how you expect them to fix it, now.gg implemented this. If you’re so adamant about it being fixed, find someone who can submit a pull request that fixes it.

**Comment by kxtzownsu** [comment]
> u shouldent be talkin shark hat man

im actually a female 😭

**Comment by 1coolmatt8083** [comment]
i meant to say shark hat girl

**Comment by proudparrot2** [comment]
Shiver me timbers

**Comment by proudparrot2** [comment]
The GitHub contribution graph says otherwise
![IMG_0101](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/71939973/6cb4072f-80ea-4f16-a04b-2b9323e0bc9d)
![IMG_0100](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/71939973/70756f30-fb9d-4b44-8e91-30916a18f078)

**Comment by 1coolmatt8083** [comment]
phht..... really is that all uv got here let me show u the new games iv coded this year
https://dddatt.github.io/bss/

**Comment by 1coolmatt8083** [comment]
https://github.com/1coolmatt8083/karlson-3d-map-builder-challenge

**Comment by 1coolmatt8083** [comment]
plz just plz help out bro

**Comment by 1coolmatt8083** [comment]
for some reson ever time i play roblox on the doge network in only shows half screen and its not like i can scroll up or anything , its like the frame forsed it to scroll up and u cant see half the screen
![Screenshot 2024-04-11 1 08 01 PM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/162379962/6adb02ca-fe3f-4e88-ae19-c50bd542a129)

**Comment by yu6x** [comment]
> they dont care about their costomers and they dont care THEY JUST DONT CARE!!

customers? this doesn't even have a price tag

**Comment by Riftriot** [comment]
Stop posting useless comments on this issue or you will be blocked from the org. Nowgg support is not planned as percs said.

**Comment by BomberFish** [comment]
how did i miss this certified banger thread

**Comment by notboeing747** [comment]
🍿

**Comment by proudparrot2** [comment]
This is an open source library. They have no customers and if they did they probably wouldn’t care if one website has issues. Plenty of other ones work just fine.

**Comment by IncognitoTGT** [comment]
@1coolmatt8083 skiddy skid

**Comment by Lunarion31** [comment]
what the hell happens in here

**Comment by Lunarion31** [comment]
@1coolmatt8083 shut the fuck up monkey

**Comment by MrUbun2** [comment]
my god this is so funny lmao

**Comment by IncognitoTGT** [comment]
lmao

**Comment by 1coolmatt8083** [comment]
which other sites would work for playing roblox without downloading because I only see now.gg offering that??

**Comment by proudparrot2** [comment]
Just look it up online or buy your own computer
Or you could just be responsible and do your schoolwork…

**Comment by IncognitoTGT** [comment]
most patient interstellar user (he makes similiar braindead issues there):

**Comment by MrUbun2** [comment]
> which other sites would work for playing roblox without downloading because I only see now.gg offering that??

well its actually quite simple
1. download roblox
2. open roblox
3. profit

**Comment by 1coolmatt8083** [comment]
dooo
