### ISSUE TITLE
Koyeb Deployment Issues

### ISSUE THREAD

**Issue by k1519035** [titaniumnetwork-dev/Ultraviolet#123]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

## I am getting an error when deploying to Koyeb.
The logs are attached.
[proxy-ultraviolet-8a569c27-cb39-4c92-8b90-47f427e0dfcb (1).txt](https://github.com/titaniumnetwork-dev/Ultraviolet/files/14750963/proxy-ultraviolet-8a569c27-cb39-4c92-8b90-47f427e0dfcb.1.txt)

**Comment by proudparrot2** [comment]
![CleanShot 2024-04-22 at 14 54 12@2x](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/71939973/95bc45b8-d468-4f43-842f-0a61910eb16e)
The issue seems to be with bare-mux's version specifier in package.json. It's been recently updated in the repository, can you try running it again?

> Sub-note, this specific repository can't be deployed to hosting platforms; this is the library for Ultraviolet. You'll want to deploy something like [Ultraviolet-App](https://github.com/titaniumnetwork-dev/ultraviolet-app) or [Ultraviolet template](https://github.com/proudparrot2/ultraviolet)
