### ISSUE TITLE
Youtube keeps adding ?themeRefresh=1, slowing down the client

### ISSUE THREAD

**Issue by itschasa** [titaniumnetwork-dev/Ultraviolet#126]
YouTube will (most of the time) will add `themeRefresh=1` as a URL param, and this causes the page to reload twice every time you click onto a new page, instead of loading quickly (where the red bar at the top of the page appears, showing loading progress)

https://github.com/titaniumnetwork-dev/Ultraviolet/assets/79016507/8edbad28-5669-4579-8cd4-47a8d7ff0ee6

As you can see in the video, loading in the browser without UV is a lot faster, as there is no redirect being done by YouTube.

**Comment by pretzer25** [comment]
whenever you are going on youtube just copy and paste the link but add themeRefresh=1 to the end, you can modify the proxy yoursely to add themeRefresh=1 to the end of the url if it doesnt exist if the url starts with https://youtube.com

**Comment by itschasa** [comment]
> whenever you are going on youtube just copy and paste the link but add themeRefresh=1 to the end, you can modify the proxy yoursely to add themeRefresh=1 to the end of the url if it doesnt exist if the url starts with https://youtube.com

that is so weird, that actually fixes it, thank you, i will edit the proxy so it will do that automagically. thanks again <3
