### ISSUE TITLE
howtomakesoap agent is not working, I search up anything and all it says is "Failed to load https://www.google.com/search?q=you  Internal Server Error  Code:	UNKNOWN there are no bare clients Try:  Checking your internet connection Verifying you entered the correct address Clearing the site data Contacting how-to-make.soapagent.com's administrator Verify the Bare server isn't censored If you're the administrator of how-to-make.soapagent.com, try:  Restarting your Bare server Updating Ultraviolet Troubleshooting the error on the GitHub repository"

### ISSUE THREAD

**Issue by reireitootact** [titaniumnetwork-dev/Ultraviolet#129]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by proudparrot2** [comment]
"there are no bare clients" is not an Ultraviolet issue. This is an issue with how the site owner set up their bare-mux transport configuration.

The website url that you listed in the title seems to be working for me. A quick way to get around this is to reload with `Ctrl + Shift + R` one or two times until it works.

**Comment by reireitootact** [comment]
it worked as soon as I commented abt it. lol but now its not working again, I guess it's just gonna do this from time to time. Thank you though

**Comment by itschasa** [comment]
https://github.com/titaniumnetwork-dev/Ultraviolet/wiki/Upgrading

**Comment by itschasa** [comment]
> it worked as soon as I commented abt it

close your issues

**Comment by Percslol** [comment]
same thing as your other issue, please use the description of the issue to list out your issue
