### ISSUE TITLE
Latest Ultraviolet does not work on 🦊 Firefox

### ISSUE THREAD

**Issue by mdoryammilwalrus** [titaniumnetwork-dev/Ultraviolet#13]
## Expected Behavior

Bigger websites (YouTube/Twitch) load content (videos/thumbnails/pages).

## Current Behavior

Bigger websites (YouTube/Twitch) fail to load content (videos/thumbnails/pages).

![image](https://user-images.githubusercontent.com/91034348/208048098-219fa63f-0db6-449f-9b05-7dbb1c2cc312.png)

It worked before and stopped working with the newer version.

This is NOT a YouTube issue, it works if you switch to a older version.

## Steps to Reproduce

1. Use Firefox. If you don't have it, download it from https://www.mozilla.org/firefox/new/
2. Clone [Ultraviolet-App](https://github.com/titaniumnetwork-dev/Ultraviolet-App) or [Incognito](https://github.com/amethystnetwork-dev/Incognito) (needs uv update) and run it
3. Open youtube.com

## Context (Environment)

Firefox 108.0
Backend running on NodeJS v18

**Comment by e9x** [comment]
This is due to issues with the Bare server's V2 protocol getting filtered by Firefox for security/privacy reasons.

**Comment by e9x** [comment]
Will not fix

**Comment by Craftzman7** [comment]
Why?

**Comment by e9x** [comment]
This issue is beyond me. Ultraviolet is merely being maintained. I suspect either this issue has already been fixed in recent Firefox releases, as I'm able to use Ultraviolet in Firefox, or it's very subtle.

**Comment by wearrrrr** [comment]
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/99224452/3336384a-9520-4020-b0db-322bd88cfd75)
@QuiteAFancyEmerald, Ultraviolet works on youtube for me with Alu, pretty sure this can be closed again.

**Comment by wearrrrr** [comment]
The icons not being there was just because I took the screenshot before it fully loaded. but it works.
