### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by reireitootact** [titaniumnetwork-dev/Ultraviolet#130]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by itschasa** [comment]
https://github.com/titaniumnetwork-dev/Ultraviolet/wiki/Upgrading

**Comment by Percslol** [comment]
please create an issue using the body of the issue instead of the title
