### ISSUE TITLE
Spotify with Ultraviolet is broken

### ISSUE THREAD

**Issue by dimseal** [titaniumnetwork-dev/Ultraviolet#131]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1. Using Ultraviolet-App 
2. Search and go to Spotify with the proxy
3.It gives the error in Inspect element 'Uncaught ReferenceError: window is not defined
    at Sc (Switcher.ts:58:22)
    at Switcher.ts:80:1
    at index.js:198:50'
4. Spotify does not load it only shows a black screen

**Comment by Notplayingallday383** [comment]
dude your incorrect. Spotify works fine on v3.1 just fine. Site support isn't really something to make GH issues about especially with literally no information

**Comment by Percslol** [comment]
fixed in latest release
