### ISSUE TITLE
Youtube isn't working

### ISSUE THREAD

**Issue by Dhako12** [titaniumnetwork-dev/Ultraviolet#133]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Dhako12** [comment]
Youtube isn't working it shows error.

**Comment by proudparrot2** [comment]
Thanks for sending that in a separate comment and not in the issue template laid out for you

If you could show us exactly what error is occurring ("not working" is extremely vague) and your Ultraviolet setup, then we can probably help you

**Comment by orvitpng** [comment]
If it shows an error, provide it... How do you expect anyone to work off of "isn't working?"

I recommend this gets closed as @Dhako12 didn't even take the care to write the issue using the template.

**Comment by Riftriot** [comment]
Badly made issue and youtube DOES work. Can't recreate
