### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by V4N1SH1** [titaniumnetwork-dev/Ultraviolet#135]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by proudparrot2** [comment]
This is extremely vague. What isn't working? What's the error? Where are you using Ultraviolet?

The issue template is for a reason - so people can help you better instead of having to ask these questions.

**Comment by Notplayingallday383** [comment]
No information was provided. Do not create stupid issues like this

**Comment by Percslol** [comment]
if you are going to make an issue, put details or follow the issue template layed out for you

closing as wont fix
