### ISSUE TITLE
Failed to register service worker. 

### ISSUE THREAD

**Issue by 1043613lcpsorg** [titaniumnetwork-dev/Ultraviolet#137]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.
When I start Ultraviolet it gives me this error 

Failed to register service worker.

ReferenceError: BareMux is not defined 

was supposed to open Google but gave me the error 
![Screenshot 2024-05-02 10 04 46 AM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/153699099/e393abb8-c9fc-40b3-aa7e-4c188f51a44d)

**Comment by proudparrot2** [comment]
What repository are you deploying? Ultraviolet-App?

**Comment by 1043613lcpsorg** [comment]
> What repository are you deploying? Ultraviolet-App?

yes

**Comment by Notplayingallday383** [comment]
This is an issue for ultraviolet-app not actual Ultraviolet

**Comment by Percslol** [comment]
cant repro, try updating your uv-app and report back if it still doesnt work

closing as wont fix
