### ISSUE TITLE
Ultraviolet not working on Interstellar?

### ISSUE THREAD

**Issue by thecumbine** [titaniumnetwork-dev/Ultraviolet#138]
## Expected Behavior:

I should be able to access sites.

## Current Behavior:
![Screenshot 2024-05-02 3 36 28 PM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/163605738/025a719b-4c0d-47e4-986e-a293f764e666)

## Possible solutions:

A solution with Interstellar is to use their "Dynamic" proxy. (UV works way better though.)

## Steps to Reproduce:

1.Open Github Codespaces
2. Start the proxy 
3. Go to any website

It prevents me from using any website on Interstellar.
## Repository to Interstellar.
https://github.com/UseInterstellar/Interstellar
sorry if sending links to repositories breaks a rule.

**Comment by Riftriot** [comment]
This is an issue with the implementation, not Ultraviolet. Make an issue on the [interstellar repo](https://github.com/UseInterstellar/Interstellar), not here.

**Comment by IncognitoTGT** [comment]
why are you making the issue here??!?!
