### ISSUE TITLE
Is there a way to enable WebGL

### ISSUE THREAD

**Issue by pretzer25** [titaniumnetwork-dev/Ultraviolet#139]
Im Using the TIW Static-Ultraviolet which i don't think should effect anything, but I deploy on Vercel which I think disables WebGL on proxies, I can't deploy anywhere else, is There a way to enable WebGL???

**Comment by proudparrot2** [comment]
Vercel wouldn't be the problem
TIW's Ultraviolet is outdated - I recommend building your own copy.

**Comment by pretzer25** [comment]
thank you, to build my own copy, can I just copy and paste all files from ultraviolet folder to my repository and just change the bare server address?

**Comment by pretzer25** [comment]
all I need to get is the uv files except host the bare server from another website

**Comment by proudparrot2** [comment]
You need to clone ultraviolet onto your machine (with node.js installed), install packages, and run `npm run build`. The ultraviolet build files will be available in the `dist` folder. Keep in mind that the latest version of ultraviolet uses wisp instead of bare, and you’ll need to find an earlier commit to clone from in order to use bare.

**Comment by JustJxrdanWasDefinetlyTaken** [comment]
> Im Using the TIW Static-Ultraviolet which i don't think should effect anything, but I deploy on Vercel which I think disables WebGL on proxies, I can't deploy anywhere else, is There a way to enable WebGL???

just deploy to cf pages

**Comment by not-amplify** [comment]
> > Im Using the TIW Static-Ultraviolet which i don't think should effect anything, but I deploy on Vercel which I think disables WebGL on proxies, I can't deploy anywhere else, is There a way to enable WebGL???
> 
> just deploy to cf pages

u realize uv v2 can just run off the external bare without having to use something outdated

**Comment by not-amplify** [comment]
oh wait i didnt scroll far up enough to see that wasnt u, mb...

**Comment by JustJxrdanWasDefinetlyTaken** [comment]
> oh wait i didnt scroll far up enough to see that wasnt u, mb...

lol its alright

**Comment by Percslol** [comment]
closing as stale
