### ISSUE TITLE
YouTube isn't working for me it says eror

### ISSUE THREAD

**Issue by therizzlybear45325** [titaniumnetwork-dev/Ultraviolet#143]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by proudparrot2** [comment]
This is extremely vague, and there could be an entire list of reasons why YouTube is having an error. It would be helpful if you could fill out the issue tracker laid out for you.

What version of Ultraviolet are you running? What is your setup? Is this occurring on your website with Ultraviolet, or are you just using a proxy site and this error is showing up?

**Comment by MeakWrld** [comment]
how to access the new release?

**Comment by proudparrot2** [comment]
Clone the repository on your machine, `npm install`, `npm run build`.

**Comment by ProgrammerIn-wonderland** [comment]
For future reference don't put your username in the title of the issue, we can already see it

**Comment by rifting** [comment]
Closed as stale
