### ISSUE TITLE
RangeError: Out of Memory" Error on Mobile Devices

### ISSUE THREAD

**Issue by markusemrys** [titaniumnetwork-dev/Ultraviolet#146]
Hi,

I'm encountering a "RangeError: Out of Memory" error when opening the web on mobile devices. Has anyone experienced a similar issue and found a solution?

Thanks!

**Comment by appleflyerv3** [comment]
maybe its because ur out of memory genius

**Comment by rifting** [comment]
Have you tried both libcurl and epoxy?

**Comment by rifting** [comment]
Fixed in https://github.com/MercuryWorkshop/EpoxyTransport/commit/016288f7edcc6bd1f6fb01e959ad357d3fa3c0da
