### ISSUE TITLE
How do I fix GeForce now.

### ISSUE THREAD

**Issue by JustJxrdanWasDefinetlyTaken** [titaniumnetwork-dev/Ultraviolet#147]
So basically geforce now is not supported for me when I use ultraviolet.
repo: https://github.com/GalacticNetwork/astro
view: https://browseastro.pro
UV Version: 3.1.2

**Comment by proudparrot2** [comment]
All sites aren't guaranteed to work and complex sites such as GeForce NOW don't

**Comment by Percslol** [comment]
GeForce Now in my testing has been compatible, can you please provide images of the error that you are recieving?
@JustJxrdanWasDefinetlyTaken

**Comment by JustJxrdanWasDefinetlyTaken** [comment]
> GeForce NOW in my testing has been compatible, can 
you please provide images of the error that you are recieving? @JustJxrdanWasDefinetlyTaken

Sure!
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/108704541/5966c972-4bc3-45f9-adc4-f9c395fb76e8)
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/108704541/f863323e-4a10-4900-806b-79f179078127)
when you press the 'get in' button it drops a 403 error
how I know it's not just me is my friend uses 3.1.2 and gets the same error
https://arc.galacticnetwork.org/

@Percslol

**Comment by JustJxrdanWasDefinetlyTaken** [comment]
proof:
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/108704541/68ec7674-7df8-47fb-b7f7-f28cf52e5a1c)
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/108704541/b1b1bb25-cc6a-4d36-837d-5cbb4cab24eb)

**Comment by KDust7** [comment]
Hello, the reason why the GeForce NOW doesn't work is because the server that UV is being hosted on is in a location that GeForce NOW does not allow. Use a different proxy server/frontend.

**Comment by KDust7** [comment]
In your case, billiger host's servers do not work with GeForceNOW. Consider switching to a different hosting provider

**Comment by itschasa** [comment]
Geforce support depends on the IP of the proxy. If it's a datacenter IP, it's usually blocked.

**Comment by DerpmanDev** [comment]
> Hello, the reason why the GeForce NOW doesn't work is because the server that UV is being hosted on is in a location that GeForce NOW does not allow. It seems that you are using BilligerHost, switch to a different hosting provider if you want GeForce support.

If GeForce returns a 403, it doesn't mean that it's because you're using BilligerHost, it's the problem with the datacenter that the provider is using. Datacenters such as the NYC Metro tend to get their IPs blacklisted

**Comment by xbubbo** [comment]
In my experience I have only gotten 403 errors if tons of traffic was sent from one IP, and it just gets rate limited with 403 errors for a few hours and then goes back to normal

**Comment by JustJxrdanWasDefinetlyTaken** [comment]
> Hello, the reason why the GeForce NOW doesn't work is because the server that UV is being hosted on is in a location that GeForce NOW does not allow. It seems that you are using BilligerHost, switch to a different hosting provider if you want GeForce support.

Thank you!
