### ISSUE TITLE
Updating to V3 - Unable to fetch Bare meta

### ISSUE THREAD

**Issue by GavinGoGaming** [titaniumnetwork-dev/Ultraviolet#156]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

Im updating to V3 using the wiki guide, and am running into errors.

## Expected Behavior
Loads UV page

## Current Behavior
Loads UV error page with "Unable to fetch Bare meta"
![image](https://github.com/user-attachments/assets/458e4e45-f068-434c-a78f-938b7bd77df8)

## Possible Solution
This is 100% a my-end issue, but I would like help on what im doing wrong.

## Code
https://hastebin.com/share/opokaforij.javascript

## Context (Environment)

Running an express server with a static set of HTML pages (compiled nextjs).

**Comment by Nebelung-Dev** [comment]
Are you setting the wisp server on the client correctly.
To set the wisp server, as of the latest version:
```html
<script src="/baremux/index.js"></script>
<script>
await connection.setTransport("/epoxy/index.mjs", [{ wisp: (location.protocol === "https:" ? "wss" : "ws") + "://" + location.host + "/wisp/" }]);
</script>
```

**Comment by GavinGoGaming** [comment]
I got it working (thank you LIch from tn support)
for anyone else having this issue:
![image](https://github.com/user-attachments/assets/f3134d8e-cb49-4eb1-b25a-35b37ba7f4af)

**Comment by SchoolTARMaster** [comment]
> Are you setting the wisp server on the client correctly. To set the wisp server, as of the latest version:
> 
> <script src="/baremux/index.js"></script>
> <script>
> await connection.setTransport("/epoxy/index.mjs", [{ wisp: (location.protocol === "https:" ? "wss" : "ws") + "://" + location.host + "/wisp/" }]);
> </script>

@Nebelung-Dev 

why did you use top-level await in a normal script? that won't work
