### ISSUE TITLE
ecommerce websites

### ISSUE THREAD

**Issue by mohamedalaaser** [titaniumnetwork-dev/Ultraviolet#16]
Some websites such as zara.com and shein.com do not open for some reason. We also have a few issues with a few other ecommerce websites. Is there a way to fix those? We would like to get in touch with you to discuss possible collaborations.

**Comment by e9x** [comment]
This sounds like an issue that would require reworking certain Ultraviolet features to fix, which may in turn break compatibility with other sides. Wontfix
