### ISSUE TITLE
dont know how to use

### ISSUE THREAD

**Issue by Jacob4354652** [titaniumnetwork-dev/Ultraviolet#17]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by e9x** [comment]
Then do not use.

**Comment by Jacob4354652** [comment]
Teach me pleaseSent from my iPhoneOn Jan 7, 2023, at 2:46 PM, David Reed ***@***.***> wrote:﻿
Then do not use.
