### ISSUE TITLE
Games don't load

### ISSUE THREAD

**Issue by MoltenWolf85** [titaniumnetwork-dev/Ultraviolet#172]
I try to play on a site called nowgg.lol, through Ultraviolet 2.00 on a site called ilovemath.global.ssl.fastly.net.
1.Go to ilovemath.global.ssl.fastly.net
2.Search ngg.frogiee.one/hub
3. Click on any game
4.Error code

**Comment by MoltenWolf85** [comment]
![Screenshot 2024-12-19 8 08 05 AM](https://github.com/user-attachments/assets/5ecf8fa8-142a-4699-8392-b275feec4c08)

**Comment by rifting** [comment]
Why are you making an issue for an old version? You do realize the point of new versions is to fix bugs like these?

**Comment by MoltenWolf85** [comment]
The new versions are blocked

**Comment by rifting** [comment]
Have you tried renaming the UV files and adding a comment with random data to them?

**Comment by MoltenWolf85** [comment]
It's on a website, not downloaded

**Comment by rifting** [comment]
I don't understand, sorry. What do you mean?

**Comment by MoltenWolf85** [comment]
The proxy is embedded onto a website, and my school has disabled Javascript on files, so I can't download it.

**Comment by rifting** [comment]
I don't see how this is an issue with Ultraviolet

**Comment by MoltenWolf85** [comment]
It is an error with ultraviolet, since that is what the site uses. You know
what... Just never mind. Thank you for your time.

**Comment by InfusedStormblessed** [comment]
How would I go about adding Ultraviolet to a Google Site?
