### ISSUE TITLE
Encode/Decode Change

### ISSUE THREAD

**Issue by iIDragonterrorIi** [titaniumnetwork-dev/Ultraviolet#18]
How do I change the encode/decode?
Or at least the code for the XOR encode/decode.

When every I change anything related it breaks. Please LMK if anyone figures it out. 

(IM NOT IN THE DISCORD, DOESN'T WORK ON ULTRAVIOLET AND IM ON SCHOOL PC)

**Comment by QuiteAFancyEmerald** [comment]
You would want to do any changes via `uv.config.js`
