### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by asdklj** [titaniumnetwork-dev/Ultraviolet#20]
How would I host this on a VPS? Are there any good VPS that I can host this on which I won't get banned on?

**Comment by QuiteAFancyEmerald** [comment]
I would recommend utilizing a provider such as Dedipath was well if you are looking for more reputable and scalable sources. Pricing and terms allow for a service utilizing Ultraviolet to thrive on and they don't rate limit if your service ever becomes exhaustive.

Back when Holy Unblocker was still busy scaling, Dedipath was a pretty supportive provider with additional bandwidth if needed. (1000 down still, just the service was using close to 70TB+ at the time per month above their temporary limit of 60TB which THEY will increase if you have a situation like HU)

https://dedipath.com

**Comment by asdklj** [comment]
Emerald, would you be able to walk me through doing this? My discord is adirman#2751
