### ISSUE TITLE
Fails to connect to Discord Web-socket

### ISSUE THREAD

**Issue by AroLucy** [titaniumnetwork-dev/Ultraviolet#21]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

Discord fails to connect to it's web-socket `wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream` Preventing discord from being usable

## Expected Behavior

For the proxy to connect to Discords web-socket when trying to use Discord 

## Current Behavior

The proxy fails to connect to the web-socket causing discord to be unusable 

## Steps to Reproduce

1. Host a UV instance using, Ultraviolet, Ultraviolet-Static, and Ultraviolet-App
2. Go to https://discord.com/login
3. Login
4. It will fail to connect to web-socket 

## Context (Environment)

Trying to use discord with a self-hosted proxy

Running on replit but was also reproducible on other services, and locally

**Comment by toydotgame** [comment]
Some traces also if anyone can decode where the issue might be:
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/64190512/5ee0260e-f1af-42a9-96d8-0624f0c410a5)
(I'm running UV NodeJS instance on Replit)
