### ISSUE TITLE
Is there a way to change the browser used by Ultraviolet? Like Brave Search instead of Google.

### ISSUE THREAD

**Issue by BypassGoGuardianPLS** [titaniumnetwork-dev/Ultraviolet#23]

**Comment by e9x** [comment]
This should have been made in https://github.com/titaniumnetwork-dev/Ultraviolet-App but whatever.

Read https://github.com/titaniumnetwork-dev/Ultraviolet-App/wiki/Customizing-your-frontend to create your custom frontend for UV app.

Modify `index.html` and look for
```html
<input
id="uv-search-engine"
value="https://www.google.com/search?q=%s"
type="hidden"
/>
```

You should understand how to change the search engine. Keep the `/search?q=%s`
