### ISSUE TITLE
`indexedDB` and `caches` not isolated between proxied websites

### ISSUE THREAD

**Issue by ruochenjia** [titaniumnetwork-dev/Ultraviolet#29]
I did a site data security test in my browser console, `localStorage` and `sessionStorage` are isolated between proxied websites, but `indexedDB` and `caches` are not. The `await caches.keys();` code in a proxied website returns exactly the same as the code in the root domain.

![image](https://user-images.githubusercontent.com/66373748/220186262-b62e8764-cde2-4083-b13f-4359bcdbbff3.png)

**Comment by e9x** [comment]
Maybe we can prefix the key with the domain origin like in stomp:
https://github.com/e9x/stomp-rewrite/blob/fe1de8170fe057bbdc5ddaf2ed1e44c54187f0dd/src/inject/modules/IndexedDB.ts#L13

caches will take longer to implement because there isn't any sort of reference/tried and true method.
