### ISSUE TITLE
Server Could Not Route Request Error

### ISSUE THREAD

**Issue by boopxyz** [titaniumnetwork-dev/Ultraviolet#3]
Currently, have my app deployed to Heroku and I got an error when loading the site up.

Ultraviolet | Error
The server could not route your request.

**Comment by e9x** [comment]
Although it would be more appropriate to open an issue in the Ultraviolet-Node repository, I will try to solve this.
Can you provide me with a link to your deployment on Heroku?

**Comment by boopxyz** [comment]
https://developmentbuild.herokuapp.com/

**Comment by boopxyz** [comment]
I've gotten it to work with rebuilding it but I ran into another issue of websites giving me 403 errors and am wondering how I can make the proxy be more "trusted"

**Comment by e9x** [comment]
> I've gotten it to work with rebuilding it but I ran into another issue of websites giving me 403 errors and am wondering how I can make the proxy be more "trusted"

You can patch the bare server to operate over a residential HTTP proxy... This isn't really supported.

**Comment by boopxyz** [comment]
> > I've gotten it to work with rebuilding it but I ran into another issue of websites giving me 403 errors and am wondering how I can make the proxy be more "trusted"
> 
> You can patch the bare server to operate over a residential HTTP proxy... This isn't really supported.

Well where can I change the proxy server?

**Comment by e9x** [comment]
I don't suggest it. It will be some amount of trouble considering you need to deploy it with your modified bare server to Heroku.

**Comment by e9x** [comment]
However, it is nonetheless possible. Here is an outline of what you will most likely do:
- purchase a sketchy/sneaker bot residential proxy
- setup bare-server-node for development
- install [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent)
- replace `const httpsAgent = new Agent` with the constructor for the https proxy agent class
- build, package it, upload to a CDN like discord, install the NPM package in your forked Ultraviolet-Node repository
