### ISSUE TITLE
Uncaught (in promise) error: service workers cannot be registered without https (Glitch Deployment)

### ISSUE THREAD

**Issue by Notplayingallday383** [titaniumnetwork-dev/Ultraviolet#30]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

Hello, I have recently deployed UV to a new Glitch Instance and am getting this issue when loading websites and the only way to get around it is to restart the server.

## Expected Behavior

It should just be able to load a website with https in it or without it
## Current Behavior

Instead it throws an error saying that the service workers cant be used without https when in this screenshot: 
![image](https://user-images.githubusercontent.com/72810050/221056988-235682a3-24d8-4984-bfc3-cc47d54d827c.png)
I did include https in the URL box
## Possible Solution

Fix the issue with the SW
## Steps to Reproduce

Example of this issue can be found on a Fork of this directory: https://bruhprox.glitch.me

1. Load the Website
2. put in a URL
3. it should throw an error
4. in the console it says the error

## Context (Environment)

I am trying to unblock games/website with this fork and it is not working 

This issue is essentially an Error that happens when loading a page from the main page (index.html)
## Detailed Description

This is an issue with the service worker not initiating without restarting the server
Issue found on: Google Chrome 110.0.5481.112 (Official Build) (64-bit)

**Comment by Notplayingallday383** [comment]
I seem to have fixed this issue by updating the NPM package from 1.0.8 beta -> 1.0.8 on glitch and the problem went away

**Comment by Notplayingallday383** [comment]
The issue has returned

**Comment by forfeited** [comment]
"To run code using service workers, you'll need to serve your code via HTTPS — Service workers are restricted to running across HTTPS for security reasons." https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

**Comment by e9x** [comment]
This doesn't look right. Unless glitch.me is refusing to issue you SSL certificates, it should be on https: by default. I'm able to use your domain (https://bruhprox.glitch.me/) without any issues. Maybe this is an issue on your end? Have you tried another browser/device?

Perhaps you can look into getting a server and domain then following the instructions in Ultraviolet-app to setup SSL? https://github.com/titaniumnetwork-dev/Ultraviolet-App/wiki/Configure-SSL

**Comment by Notplayingallday383** [comment]
I will see if this works on Windows but I get that issue on ChromeOS 110 however I don't have any money to spend on a server/domain and I would use freenom but its been broken for several weeks

**Comment by Notplayingallday383** [comment]
After testing it on Windows and ChromeOS again it seems to be working because the web certifficate is valid so I think the issue is what you guys said and its Glitch sometimes ins't registering SSL Certifficates.
