### ISSUE TITLE
Add support for switching server dynamically

### ISSUE THREAD

**Issue by ruochenjia** [titaniumnetwork-dev/Ultraviolet#34]
The server address is hard-coded in `uv.config.js` and cannot be easily changed during runtime. I wish to add an option to do this so users can switch server if the default one is blocked.

**Comment by cohenerickson** [comment]
It is bad practice to use the default `uv.config.js`, instead you should create your own and host it in your static directory. If you configured express routes correctly this should override the config provided by the package.

**Comment by ProgrammerIn-wonderland** [comment]
You can probably edit the file to have worker posrMessages to change it, I believe this goes beyond scope of UV itself and is up to the maintainer though
