### ISSUE TITLE
videos error 

### ISSUE THREAD

**Issue by DIVISIONSolar** [titaniumnetwork-dev/Ultraviolet#36]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

Load all videos with no issue

## Current Behavior

some videos load, others output a 404 or 403 error

## Steps to Reproduce

go to randomassfights.live and click on one of the schools

1. load randomassfights.live
2. click on Franklin HS or Oil City HS
3.
4.

**Comment by DIVISIONSolar** [comment]
found another error, happens on all websites

yntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
fetch @ uv.sw.js:282

**Comment by DaSkoolMan** [comment]
> 

not a UV issue, you are using glitch which limits requests from the proxy

**Comment by DIVISIONSolar** [comment]
> > 
> 
> not a UV issue, you are using glitch which limits requests from the proxy

I'm not using Glitch.
I'm using debian

**Comment by DaSkoolMan** [comment]
on a private VPS? dedicated? which hosting platform

**Comment by DIVISIONSolar** [comment]
It's on a VPS on one of my dedicated machines @ tier.net. I also tried it on a VPS @ hetzner

**Comment by DaSkoolMan** [comment]
> It's on a VPS on one of my dedicated machines @ tier.net. I also tried it on a VPS @ hetzner

I use linode and digital ocean and never have had this problem. My suggestion is when you get this error refresh the page to get the error.

**Comment by DIVISIONSolar** [comment]
There's no error
