### ISSUE TITLE
Processing non-ASCII characters in cookies

### ISSUE THREAD

**Issue by KaneOne** [titaniumnetwork-dev/Ultraviolet#40]
https://github.com/titaniumnetwork-dev/Ultraviolet/blob/d7369a3ef7ea11c7dccdb316574e74f30185fc2b/src/uv.sw.js#L128-L139
Some non-English websites may include non-ASCII characters in cookies. This will cause an error message indicating illegal characters in the cookie, whether when assembling headers in bareClient's fetch or when sending requests to external servers in bareServer, such as 
"Failed to execute 'set' on 'Headers': String contains non ISO-8859-1 code point". Therefore, filtering out non ISO-8859-1 characters before calling bareClient.fetch can temporarily solve this problem.
I added the following line of code.
```javascript
if (requestCtx.headers['cookie']) {
  // eslint-disable-next-line no-control-regex
  requestCtx.headers['cookie'] = requestCtx.headers['cookie'].replace(/[^\x00-\xFF]/g, "")
}
 const response = await this.bareClient.fetch(fetchedURL, { 
     headers: requestCtx.headers, 
     method: requestCtx.method, 
     body: requestCtx.body, 
     credentials: requestCtx.credentials, 
     mode: 
         location.origin !== requestCtx.address.origin 
             ? 'cors' 
             : requestCtx.mode, 
     cache: requestCtx.cache, 
     redirect: requestCtx.redirect, 
 }); 
```

**Comment by e9x** [comment]
This test should be added when the cookie is being set, possibly in the `setCookies` function or in any place where cookies are being parsed.
https://github.com/titaniumnetwork-dev/Ultraviolet/blob/d7369a3ef7ea11c7dccdb316574e74f30185fc2b/src/rewrite/cookie.js#L68
We could create a wrapper for set-cookie-parser that does this.

**Comment by KaneOne** [comment]
> This test should be added when the cookie is being set, possibly in the `setCookies` function or in any place where cookies are being parsed.
> 
> https://github.com/titaniumnetwork-dev/Ultraviolet/blob/d7369a3ef7ea11c7dccdb316574e74f30185fc2b/src/rewrite/cookie.js#L68
> 
> 
> We could create a wrapper for set-cookie-parser that does this. Cookies are parsed in multiple places.

u r right.
