### ISSUE TITLE
nginx reverse proxy with password,then ultraviolet don't work.

### ISSUE THREAD

**Issue by ultraplusgithub** [titaniumnetwork-dev/Ultraviolet#41]
when I use nginx proxy ultraviolet with basic auth,then ultraviolet will don't work,but once I use nginx proxy ultraviolet without baisc auth,then ultraviolet will work.

this is bug picture(when use nginx proxy with basic auth)
<img width="401" alt="image" src="https://user-images.githubusercontent.com/129269566/228476953-39dee903-90b7-4f52-9980-70544c3e1884.png">
my ultraviolet version is 1.0.11,nginx version is 1.18.0,Ubuntu 22.04.2LTS

nginx config:
	location / {
		proxy_pass http://127.0.0.1:10002/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection Upgrade;
		proxy_set_header Host $host;
	}

**Comment by CodingCody-1** [comment]
I am having an identical issue to yours. The only difference in our setups is that I am using Ubuntu 20.04 with docker. I did test that disabling the password though nginx didn't fix the issue.

**Comment by yusanshi** [comment]
Don't add basic auth at Nginx level, but in Node.js express.js, then it can work well.

Simple example:
```bash
npm install express-basic-auth
```
```diff
diff --git a/src/index.js b/src/index.js

 import { uvPath } from "@titaniumnetwork-dev/ultraviolet";
 import { join } from "node:path";
 import { hostname } from "node:os";
+import basicAuth from "express-basic-auth";
 
+app.use(
+  basicAuth({
+    users: { username: "password" },
+    challenge: true,
+  })
+);
+
```


Refer: <https://stackoverflow.com/questions/23616371/basic-http-authentication-with-node-and-express-4>

**Comment by urasdbwd** [comment]
no, this blocks the bare.
