### ISSUE TITLE
iframes of Ultraviolet don't work

### ISSUE THREAD

**Issue by super-15** [titaniumnetwork-dev/Ultraviolet#42]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

Iframes dont work with Ultraviolet, it says "your browser doesnt support service workers" after clicking "register service workers" in an embed.
## Expected Behavior

You should be able to click "register service worker" and see the website through a proxy
## Current Behavior

When clicking "register service worker" it says "your browser doesnt support service workers"
## Possible Solution

The Ultraviolet code could be modified to detect iframes or embedded content and handle service worker registration differently in those cases. This could involve creating a separate registration process for embedded content or modifying the existing registration process to work within iframes.
## Steps to Reproduce

1.Visit a website with the proxy
2.Copy your URL (eg. https://ultraviolet-username.koyeb.app/uv/service/hvtrs8%2F-1t1%2Clml-)
3.Make an iframe on your website with that URL (<iframe src="https://ultraviolet-super-15.koyeb.app/uv/service/hvtrs8%2F-1t1%2Clml-">)
4.Click "Register Service Worker"

## Context (Environment)

I can't embed any website using the proxy. I'm trying to make an unblocked game website. I can open it in a new tab but thats annoying.

## Detailed Description

To use different HTML code (something other than iframes) or "allow" service workers in embeds/iframes in Ultraviolet.

**Comment by e9x** [comment]
If service worker support isn't detected and the website is under HTTPS, there's likely a security issue.

**Comment by super-15** [comment]
It works in a new tab (its only on embeds), and the website is HTTPS.

**Comment by IlanLuci** [comment]
From my experience using UV through iframes/embeds:

It seems that embed elements do not support service workers in general

Iframe elements will work but it often requires some messing with cors on the bare server and for some proxied sites allowing certain features within the iframe tag.

This is using the newest version of UV as of this week and bare V2.
