### ISSUE TITLE
The download function is not working

### ISSUE THREAD

**Issue by lizncoder** [titaniumnetwork-dev/Ultraviolet#46]
The download function is not working, such as downloading zip files or PNG images, and the returned format is a file with the extension .osk. How can this be resolved?
![image](https://user-images.githubusercontent.com/21351145/231097584-481a024e-1185-4a02-980d-5c7ffb0620b8.png)

**Comment by ProgrammerIn-wonderland** [comment]
The name is simply encoded, just change the extension to the correct type, will keep this open though as it's a bug, though I am unsure of how it may be fixed, or if it will be

**Comment by ThinLiquid** [comment]
> The download function is not working, such as downloading zip files or PNG images, and the returned format is a file with the extension .osk. How can this be resolved? ![image](https://user-images.githubusercontent.com/21351145/231097584-481a024e-1185-4a02-980d-5c7ffb0620b8.png)

use the plain encoder...

**Comment by mdoryammilwalrus** [comment]
These file downloading bugs are why you should still have [Corrosion](https://github.com/titaniumnetwork-dev/Corrosion) as a option on your proxy site...
