### ISSUE TITLE
Roblox

### ISSUE THREAD

**Issue by TyeeTyee** [titaniumnetwork-dev/Ultraviolet#48]
I dont know how this works but, the ngg game url or something for roblox isn't working i don't know what is happening but  i put in the code ngg.798sc.com and i press roblox on the https://fantasy-half-curler.glitch.me/ site and it doesn't work. Am i doing something wrong?

**Comment by zantili** [comment]
idk how to use this app and know u cant use roblox

**Comment by Wildtick** [comment]
Use this ⁠https://tinyurl.com/4tvuynnh
2.Search Ultrasurf in chrome web store
3.Download the VPN
4.Turn the VPN on and go on to the now.gg 
5. stop flooding this with roblox

**Comment by TestingUser1000** [comment]
Hmm I think I can do something with this...

**Comment by TestingUser1000** [comment]
Hail David Reed
e9x!!

**Comment by Garnsha011** [comment]
Now the issue with that @Wildtick is that when i try it in my chrome browser it says {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-783591ab684acabf1b81b18f79b0e042-64aac9e606693831-00"} so i don't know what is happening with that but i would appreciate some help.

**Comment by Wildtick** [comment]
> 

ok dm me on discord Wild#1380

**Comment by Garnsha011** [comment]
I will when i have time.

**Comment by GavinGoGaming** [comment]
beta6.apktbg.com/class?domain=roblox
this uses uv
your welcome

**Comment by Matthewizlitz** [comment]
how do get everything unblocked???!?!!?!??!?1/!??!?!?!?!?!?!?!??!?!
