### ISSUE TITLE
Proxy server is down.

### ISSUE THREAD

**Issue by CorruptionVR** [titaniumnetwork-dev/Ultraviolet#50]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

Proxy server to work

## Current Behavior

CLoudflare is down

## Steps to Reproduce

https://uv.radon.games/bare1/
https://uv.hypertabs.cc/bare1/
1.
2.
3.
4.

**Comment by TheMemeSniper** [comment]
🐟

**Comment by ProgrammerIn-wonderland** [comment]
Idiot

**Comment by Shadow-Afton** [comment]
The proxy been down since yesterday. When will it be back up?

**Comment by ProgrammerIn-wonderland** [comment]
This is the issue tracker for UV itself, not public deployments, please raise your issues with the deployer and not the project
