### ISSUE TITLE
Proxy server down or not working

### ISSUE THREAD

**Issue by Shadow-Afton** [titaniumnetwork-dev/Ultraviolet#53]
_Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

## Possible Implementation

_

**Comment by Woosh9129** [comment]
Not a UV problem, hosting problem.

**Comment by Shadow-Afton** [comment]
its down again i'm guessing a hosting problem again?

**Comment by genericness** [comment]
Send the error? You're issue will be closed if you don't explain further.

**Comment by Shadow-Afton** [comment]
alright
