### ISSUE TITLE
Ultraviolet is not working. I have tried deploying with different vps (5 to 6), and double checked github repos.

### ISSUE THREAD

**Issue by ItsCharzion** [titaniumnetwork-dev/Ultraviolet#54]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Possible Solution
Check code

## Steps to Reproduce

1. 
2.
3.
4.

## Detailed Description

Ultraviolet is not working. I have tried deploying with different vps (5 to 6), and double checked github repos.
Each time I deploy ultraviolet on a vps, it does not work. Was working for past 3 months, suddenly stopped working.

**Comment by GreenyDEV** [comment]
This issue is invalid because did not fill out the fields. 
You can't just say " ITS NOT WORKING!!!" and expect developers to read your mind, you have to actually provide some important information, not just complain.

**Comment by ItsCharzion** [comment]
Hey, Sorry about that.
Deployment works, but each time I try to search up something on the proxy, it shows the error
"Cannot GET /service/hvtr%3A-%2Ffiqcmrf.aoo%2Fcpr"
https://william-he-itscharzion.koyeb.app/
You may try yourself.
