### ISSUE TITLE
Proxy keeps crashing

### ISSUE THREAD

**Issue by Shadow-Afton** [titaniumnetwork-dev/Ultraviolet#55]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Shadow-Afton** [comment]
I just want to listen to my music and read fanfics peacefully but I can't do that since it keeps crashing.

**Comment by thonkinator** [comment]
most detailed uv bug report

**Comment by cohenerickson** [comment]
@Shadow-Afton Please supply more information in order to figure out what the issue actually is.

**Comment by Shadow-Afton** [comment]
alright thanks.
