### ISSUE TITLE
Ultraviolet is not working. I have tried deploying with different vps (5 to 6), and double checked github repos.

### ISSUE THREAD

**Issue by ItsCharzion** [titaniumnetwork-dev/Ultraviolet#56]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

Loading the site properly

## Current Behavior
Throws the error:
look at the image:

![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/106410330/73994a9e-fed9-4600-b685-0b535b1bf1ae)

<<p style="color: rgb(0, 0, 0); font-family: Tinos; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Failed to load<span> </span><b id="fetchedURL">http://discord.com/app</b></p><p id="errorMessage" style="color: rgb(0, 0, 0); font-family: Tinos; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Internal Server Error</p>

Code: | SyntaxError
-- | --

https://william-he-itscharzion.koyeb.app/

## Possible Solution

Updating your code

## Steps to Reproduce

1.
2.
3.
4.

**Comment by cohenerickson** [comment]
This isn't an issue with Ultraviolet, this is an issue with your bare server being unreachable.

**Comment by ProgrammerIn-wonderland** [comment]
It seems like increasing koyeb is problematic

**Comment by ItsCharzion** [comment]
Railway throws the same error 
https://nebula-production-f63a.up.railway.app/

**Comment by genericness** [comment]
This is Nebula, not Ultraviolet. Please go to them, not us.
