### ISSUE TITLE
How to turn a UV url into a normal url?

### ISSUE THREAD

**Issue by non-reai** [titaniumnetwork-dev/Ultraviolet#57]
It seems the UV url is encoded but how can you decode it and turn it into a normal url?

**Comment by proudparrot2** [comment]
I think you can use  __uv$config.decodeUrl(url)
It can’t have the /service/ or whatever your prefix is before it afaik

**Comment by proudparrot2** [comment]
wherever you want to decode it and you have __uv$config available

**Comment by non-reai** [comment]
oh my god this is the wrong repository i meant to post this on the ultraviolet app 💀

**Comment by ProgrammerIn-wonderland** [comment]
The same issue can be applied to both but ok, closing anyways then
