### ISSUE TITLE
Proxy keeps crashing pt 2

### ISSUE THREAD

**Issue by Shadow-Afton** [titaniumnetwork-dev/Ultraviolet#58]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Shadow-Afton** [comment]
I just want people and myself to have a proxy thats running smoothly and if we don't there will be more bug reports saying the Proxy's not working or it keeps crashing every 1 to 15 minutes then what or the proxy is down and you just tells it's a hosting problem then all of the other proxy I used was a hosting problem to I may have an IQ score of 95 but I'm way smarter than people think I can find a pathway in humans in a big crowd just to get away from my attacker. If I could help I would but I don't know that much about coding so that i'm not so great at.

**Comment by ProgrammerIn-wonderland** [comment]
> Try making the proxy have less issues.

We can't do much without debug logs, we don't know what's causing your proxy in particular to crash, if it's your connection, if it's some filter interfering, or what not, this isn't really a helpful issue.
