### ISSUE TITLE
now.gg proxy detected, yet "supported" in readme

### ISSUE THREAD

**Issue by GavinGoGaming** [titaniumnetwork-dev/Ultraviolet#59]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior
Now.gg loads whatever game

## Current Behavior

"Proxy/VPN detected" popup.
<img width="407" alt="Screen Shot 2023-05-15 at 6 45 22 PM" src="https://github.com/titaniumnetwork-dev/Ultraviolet/assets/57292172/db4d5cb1-cc09-4cfd-95db-815f7678afa2">

## Possible Solution

According to [stackoverflow](https://superuser.com/questions/481879/is-there-a-way-to-prevent-web-services-from-knowing-that-i-am-using-a-proxy-to-c), if ultraviolet does not send XFF headers it is much harder to detect VPNs. 

## Steps to Reproduce

1. open your proxy of choice using UV (i use hypertabs)
2. type in a now.gg game link
3. see the popup
4. doesnt work

## Context (Environment)

I am trying to play games like Among Us or Roblox and now.gg is the only popular option that I can find.

## Detailed Description

I am proposing a way to block proxy detection.

## Possible Implementation

Add option to not send XFF headers (or im just being dumb and this already exists)

**Comment by genericness** [comment]
This isn't a UV issue. I have used UV on now.gg fine. 

Please close this issue admins

**Comment by forfeited** [comment]
this is a host issue 💀  not a uv issue lmaooo
