### ISSUE TITLE
Proxy down again

### ISSUE THREAD

**Issue by Shadow-Afton** [titaniumnetwork-dev/Ultraviolet#60]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Current Behavior: Link won't open it keeps saying. 
Your service is almost ready!
We are deploying your application. Refresh this page in a few seconds or check out your deployment status in the Koyeb [control panel](https://app.koyeb.com/).

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Shadow-Afton** [comment]
I've refreshed it a bunched of times and it doesn't go back after refreshing it.

**Comment by ProgrammerIn-wonderland** [comment]
Oh and this repo isn't deployable

**Comment by Shadow-Afton** [comment]
How long will it take to be back up and running?

**Comment by ProgrammerIn-wonderland** [comment]
This isn't a UV issue

**Comment by Shadow-Afton** [comment]
You said it was a host issue how long will it be back up and running again. ?

**Comment by ProgrammerIn-wonderland** [comment]
Ask the host, not us

**Comment by Shadow-Afton** [comment]
alright.
