### ISSUE TITLE
cant get past hcapcha

### ISSUE THREAD

**Issue by powerCord1** [titaniumnetwork-dev/Ultraviolet#61]
![Screenshot 2023-05-30 9 07 15 AM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/108046909/587bd6bd-c73b-43ea-a9e5-abe57bbb64d9)
this is the response i get when submitting a hcapcha test.
i used this on discord and it doesnt let me log in

**Comment by swettyboy69** [comment]
i'm using holy unblocker

**Comment by CycloKid** [comment]
> i'm using holy unblocker

this is the repository for ultraviolet, not holy unblocker. ultraviolet is a newer proxy that works much better. also holy unblocker is not supported anymore

**Comment by wearrrrr** [comment]
> this is the repository for ultraviolet, not holy unblocker. ultraviolet is a newer proxy that works much better. also holy unblocker is not supported anymore

both use the same underlying proxy, holy-ub is just a frontend for ultraviolet with same additional features practically. It's the exact same speed in practice because both use UV and bare servers

**Comment by swettyboy69** [comment]
> > this is the repository for ultraviolet, not holy unblocker. ultraviolet is a newer proxy that works much better. also holy unblocker is not supported anymore
> 
> both use the same underlying proxy, holy-ub is just a frontend for ultraviolet with same additional features practically. It's the exact same speed in practice because both use UV and bare servers

yeah i know
im getting the error from ultraviolet

**Comment by swettyboy69** [comment]
> > this is the repository for ultraviolet, not holy unblocker. ultraviolet is a newer proxy that works much better. also holy unblocker is not supported anymore
> 
> both use the same underlying proxy, holy-ub is just a frontend for ultraviolet with same additional features practically. It's the exact same speed in practice because both use UV and bare servers

okay now the uv.* requests are fetching fine
i cant see the captcha anymore though and thats an error from hu proxy
