### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by nyabugz** [titaniumnetwork-dev/Ultraviolet#65]
everytime I try going to the website it shows me error!
![Screenshot 2023-08-18 12 35 45 AM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/137914183/d0ca5b1b-56b0-4a82-86c4-dea2ae84675f)
I'm on chrome so idk if it's like this for everyone

**Comment by justDarian** [comment]
Im having the same issue. Running latest version of Bare and Ultraviolet.

**Comment by proudparrot2** [comment]
Probably a firewall issue, it can’t make any external requests

**Comment by justDarian** [comment]
@proudparrot2 it was because i messed up config lol

**Comment by ProgrammerIn-wonderland** [comment]
This is caused by a not working bare server

**Comment by plooshi** [comment]
> everytime I try going to the website it shows me error! ![Screenshot 2023-08-18 12 35 45 AM](https://user-images.githubusercontent.com/137914183/261501607-d0ca5b1b-56b0-4a82-86c4-dea2ae84675f.png) I'm on chrome so idk if it's like this for everyone

the domain for that one expired; use a newer link like https://plooshidocs.online

**Comment by plooshi** [comment]
thank you mr e nine x
