### ISSUE TITLE
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by chingX64** [titaniumnetwork-dev/Ultraviolet#66]
I keep getting this issue on sites like discord.com/login and github.com
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/116446349/7d7c00a7-dcb9-4a21-9f72-c9e1808839ed)

**Comment by justDarian** [comment]
Same with v2 btw

**Comment by Notplayingallday383** [comment]
Seems like a bare issue check that the bare isn't blocked

**Comment by Woosh9129** [comment]
how is this a bare issue? it dosent work for me either.... and im using it on a personal device for testing. @e9x @Notplayingallday383

**Comment by Notplayingallday383** [comment]
Usually that error indicates a bare error however I could be wrong

**Comment by ProgrammerIn-wonderland** [comment]
Ah ok, I know this issue because I was just recently facing it! The issue is with your reverse proxy (nginx) and the header sizes, you need to configure nginx to allow bigger headers

**Comment by idk-pixel** [comment]
@ProgrammerIn-wonderland Correct, i fixed it before your comment but still thanks for share
