### ISSUE TITLE
UV doesn't appear to handle srcsets correctly...

### ISSUE THREAD

**Issue by Titanium2099** [titaniumnetwork-dev/Ultraviolet#67]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

UV doesn't seem to replace srcsets correctly

## Current Behavior
I except it to replace the links in the srcset with UV links

## Possible Solution
Not sure, because UV seams to normally be able to replace srcsets...

## Steps to Reproduce

1. start UV
2. go to https://poki.com
3. All the images are broken (assuming poki.com is blocked) if you look more closely you can see that it is something like this:
```html
<picture class="sc-18mcksl-0 KeCrn">
    <source srcset="https://img.poki.com/cdn-cgi/image/quality=78,width=314,height=314,fit=cover,f=auto/ee9ca3764ef4289a48a1ebf457ef605441ed1f35a0f2eb12707a70d609e53686.png 1x, https://img.poki.com/cdn-cgi/image/quality=78,width=628,height=628,fit=cover,f=auto/ee9ca3764ef4289a48a1ebf457ef605441ed1f35a0f2eb12707a70d609e53686.png 2x" media="(min-width: 1541px)" width="314" height="314"><img __uv-attr-src="https://img.poki.com/cdn-cgi/image/quality=78,width=204,height=204,fit=cover,f=auto/ee9ca3764ef4289a48a1ebf457ef605441ed1f35a0f2eb12707a70d609e53686.png" src="https://vigilant-tribble-g4qwg5wv4jx9cpqp-8080.app.github.dev/uv/service/hvtrs8%2F-iog%2Cpmkk.aoo%2Fadl-agk%2Fkmcgg%2Fsuclkt%7B%3D58.wkdvh%3F224.hgiehv%3D006%2Cdiv%3Daotep%2Cd%3Dcuvo-eg9aa1744gf62%3A9c4%3Aa3e%60f655ed625643ef1d37a2f0e%6010727c72d40%3Be73484.rne" alt="Retro Bowl" srcset="https://img.poki.com/cdn-cgi/image/quality=78,width=204,height=204,fit=cover,f=auto/ee9ca3764ef4289a48a1ebf457ef605441ed1f35a0f2eb12707a70d609e53686.png 1x, https://img.poki.com/cdn-cgi/image/quality=78,width=408,height=408,fit=cover,f=auto/ee9ca3764ef4289a48a1ebf457ef605441ed1f35a0f2eb12707a70d609e53686.png 2x" loading="eager" decoding="async" width="204" height="204" class="sc-18mcksl-1 eoBBYj">
</picture>
```
5. You can see that the srcset is still `https://img.poki.com/cdn-cgi/image/quality=78,width=314,height=314,fit=cover,f=auto/ee9ca3764ef4289a48a1ebf457ef605441ed1f35a0f2eb12707a70d609e53686.png 1x, https://img.poki.com/cdn-cgi/image/quality=78,width=628,height=628,fit=cover,f=auto/ee9ca3764ef4289a48a1ebf457ef605441ed1f35a0f2eb12707a70d609e53686.png 2x`  instead of being a UV link

**Comment by Jokypond** [comment]
does this happen to other websites or just poki?

**Comment by Titanium2099** [comment]
Yes it appears that it does it also for https://crazygames.com
