### ISSUE TITLE
Game Issues on UV

### ISSUE THREAD

**Issue by Notplayingallday383** [titaniumnetwork-dev/Ultraviolet#68]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

So on my Proxy site Sodium, I have been having issues with Ultraviolet and games be loaded within it have been having issues. Those games consist of the following:

- Retrobowl (Game Loads then turns into a green screen) 
[retrobowl.log](https://github.com/titaniumnetwork-dev/Ultraviolet/files/12641810/retrobowl.log)
- Subway Surfers Web (Appears to be a cache error and it never loads and is stuck on 0%)
[subwaysurf.log](https://github.com/titaniumnetwork-dev/Ultraviolet/files/12641811/subwaysurf.log)
- Chrome Dino (The page loads but the game doesn't)
[chromedino.log](https://github.com/titaniumnetwork-dev/Ultraviolet/files/12641812/chromedino.log)
Some other games have other issues but in the end they load and are at _least playable_

## Expected Behavior

The games should load inside of the iframe without any issues.

## Current Behavior

The game either refuses to load or loads the page but the game itself is nowhere to be found

## Possible Solution

Try and Fix (If that is indeed the issue) WebGL/Unity or other commonly used web game technology's

## Steps to Reproduce

1. Visit my Proxy site [here](https://sodium-5h8.pages.dev)
2. Skip the welcome page & changelogs
3. Either search for the game using the search or go to games and select either Retrobowl, Chrome Dino, or Subway Surfers
4. See the Error in Action when loading or trying to play these games

## Context (Environment)

I am trying to built in games to my proxy site and make sure they are compatible and work.

## Detailed Description

So Recently on my proxy site I decided to finally go through and test the games and me and some of the other people who daily drive my proxy site have said the same things that I have found where the games I mentioned do not load or load but the content of the game don't load.

**Comment by Titanium2099** [comment]
I am also having a similar problem #67 (game site related), retrobowl seams to load fine via poki.com tho

**Comment by Notplayingallday383** [comment]
Was this issue fixed/resolved?
