### ISSUE TITLE
Error message when trying to load into roblox 

### ISSUE THREAD

**Issue by DublinDU** [titaniumnetwork-dev/Ultraviolet#69]
The screen just turns black and doesn't load and sometimes it will show me an error message.

**Comment by ProgrammerIn-wonderland** [comment]
How would you even load Roblox on the browser without a cloud streaming service?

**Comment by AverageJuliet** [comment]
better question: why  are you trying to play roblox, there are far better uses of your time!

**Comment by ProgrammerIn-wonderland** [comment]
Juliet, how many of these comments will you make?

**Comment by AverageJuliet** [comment]
i honestly don't know.

**Comment by Jokypond** [comment]
now.gg bypass not work?! crazy

**Comment by DublinDU** [comment]
> better question: why are you trying to play roblox, there are far better uses of your time!

Why don't you go fucking touch some grass because I can do whatever I want

**Comment by DublinDU** [comment]
> now.gg bypass not work?! crarzy

Wow bud that was very helpful

**Comment by AverageJuliet** [comment]
> > better question: why are you trying to play roblox, there are far better uses of your time!
> 
> Why don't you go fucking touch some grass because I can do whatever I want

touch deez nuts, gottem.

**Comment by ninjaWolf8724** [comment]
it's not even possible to run roblox in a browser without a cloud streaming service it's a native app lol

**Comment by DublinDU** [comment]
It is possible LOL because I have done it before using now.gg

**Comment by Jokypond** [comment]
> 
> It is possible LOL because I have done it before using now.gg 

that's not native, its run on now.gg's server which is then broadcasted to your device (GeForce Now but for android)
