### ISSUE TITLE
Discord on ultraviolet using cyclic

### ISSUE THREAD

**Issue by Louis654** [titaniumnetwork-dev/Ultraviolet#7]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

discord isnt providing a qr code on the login page
also manual login using a account results in discord thinking this is a bot login

i should be able to log in using my phone with the qr code

the qr code is on endless loading and never appears

i dont know whats causing this

https://easy-pear-crayfish-tutu.cyclic.app/uv/service/hvtrs8%2F-dksaopd%2Ccmm-lmgkn
1. go to discord on ultraviolet
2. go to login
3. no qr code
4.

## Context (Environment)

im trying to use discord on chrome os and cyclic was the only unblocked hosting site

i want to use discord on my chromebook

**Comment by BubblePlayzTHEREAL** [comment]
your link doesn't work. You could try [mine](google.bubl.ga)
