### ISSUE TITLE
hashtags

### ISSUE THREAD

**Issue by ambi-s** [titaniumnetwork-dev/Ultraviolet#73]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

basically on some sites you have links that redirect to a hastag, for example: `example.com/#hashtag/page/here`.
this doesn't work all the time on ultraviolet

## Expected Behavior

the link should give me the correct page

## Current Behavior

it basically just reloads the page without applying the hashtag

## Possible Solution

idk

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

I'm trying to use mail.com because my school blocks all emails not from within the school district to my school email. but on mail.com they blocked it, but when I use ultraviolet since mail.com uses the hashtag thing to launch the login forum, it doesn't work

**Comment by Notplayingallday383** [comment]
Could you provide the code you used for this? I can send you a UV encoder html doc where it’s like example.com/encode.html#https://google.com if that’s what you mesnt
