### ISSUE TITLE
when i want to play rocket leuge in geforce its say for me error 0x000001f8

### ISSUE THREAD

**Issue by dswrssd** [titaniumnetwork-dev/Ultraviolet#75]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by non-reai** [comment]
what the hell is this

**Comment by tuta-amb** [comment]
Honestly, [no one cares](https://www.youtube.com/watch?v=BLUkgRAy_Vo). Probably something broke/corrupted during the proxy-ing process with WebGL or something. Also, can you spell? Finally, if you're on a device where you need a proxy to unblock things, this device must have trash specs. So why are you attempting to play a quality game on it? What performance are you expecting?

**Comment by non-reai** [comment]
FR!!!!!

**Comment by zkayns** [comment]
😁👌👌👌👌👌👌👌

**Comment by Jokypond** [comment]
so true

**Comment by KELP1234** [comment]
rocket leuge

**Comment by Percslol** [comment]
fixed in uv 3.1.0 (commit d41d56c17df8834f4a08585c82bcecb3240cf756)
