### ISSUE TITLE
amethystnetwork-dev/Incognito Not Working on Hop.sh

### ISSUE THREAD

**Issue by M1noa** [titaniumnetwork-dev/Ultraviolet#77]
## Issue

![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/57844837/876a7e42-70bf-4004-b40a-ac514a92f62f)

I can't access most sites like [https://discord.com/app](https://discord.com/app), [https://search.brave.com](https://search.brave.com), TikTok, etc. But some sites do work, like Google.

I'm using [https://github.com/amethystnetwork-dev/Incognito](https://github.com/amethystnetwork-dev/Incognito) hosted on hop.sh. I feel like the culprit of this bug is hop.sh due to me getting `RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].` on an older version of amethystnetwork-dev/Incognito that used Ultraviolet v1. I don't see anything in the logs about any errors or anything and this same error happens with other Ultraviolet proxies.

**Comment by Jokypond** [comment]
doctype is not valid json!!!!

**Comment by tuta-amb** [comment]
> doctype is not valid json!!!!

What does this have to do with anything?

**Comment by Jokypond** [comment]
> > doctype is not valid json!!!!
> 
> What does this have to do with anything?

doctype is not valid json bro, do you not understand

**Comment by tuta-amb** [comment]
> > > doctype is not valid json!!!!
> > 
> > 
> > What does this have to do with anything?
> 
> doctype is not valid json bro, do you not understand

Please provide more context. While the string `doctype` certainly is not valid JSON, that is irrelevant to the issue?

**Comment by DoxrGitHub** [comment]
syntax error says "doctype" (it by itself is probably not related to anything, the entire HTML is being used as json somehow which gives that error, `<DOCTYPE html>` is probably the first line in the html/json)

**Comment by Deovolentezz** [comment]
Hello, I met the same problem, do you know how to solve it?

**Comment by Percslol** [comment]
this issue should be opened up in the incognito repo, closing now.

**Comment by proudparrot2** [comment]
I’ve noticed that the RangeError typically means that the Bare server cannot reach the public internet

**Comment by proudparrot2** [comment]
> syntax error says "doctype" (it by itself is probably not related to anything, the entire HTML is being used as json somehow which gives that error, `<DOCTYPE html>` is probably the first line in the html/json)

It basically just means that instead of getting a valid JSON object, it instead got an HTML document which typically means that the expected JSON endpoint doesn’t exist or can’t be reached
