### ISSUE TITLE
sites and search 

### ISSUE THREAD

**Issue by Envyme1314** [titaniumnetwork-dev/Ultraviolet#78]
## Current Behavior

it gives me a cant fetch screen when i was just using it 10 minutes ago. i dont know what happened between that time and now, but it also isnt allowing me to open the icons like discord or twitter. 
1

![Screenshot 2023-10-11 6 41 48 PM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/147668695/f43dacdd-6d40-4a07-8880-2da58e9e303f)

**Comment by Riftriot** [comment]
Closed as stale
