### ISSUE TITLE
TypeError while running on Google Cloud Shell

### ISSUE THREAD

**Issue by tuta-amb** [titaniumnetwork-dev/Ultraviolet#79]
I'm running this app on Google Cloud Shell Preview, and before you recommend another platform: 
1. Every single app host is blocked, only reason Google Cloud Shell isn't is because all Google domains have a hard coded whitelist.
2. Shell Preview gives 50 hours a week of free usage
3. My school trusts any google.com domain

However when deploying any Ultraviolet-based proxy, namely github.com/titaniumnetwork-dev/Ultraviolet-App and Holy Unblocker, I get the following error:
```
Error processing your request
Failed to load https://www.google.com/search?q=test
Internal Server Error
Code:	TypeError
TypeError: Failed to fetch
```
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/146651411/986a4a89-d48c-4793-b0f1-b29b20a67a2c)
Also, when deploying a simple TompHTTP bare server from NodeJs, I get the following 401 error:
```
RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].
```
Issue #78 seems to have a identical problem. This is probably related to #77 and tomphttp/bare-server-node/issues/17. On the TompHTTP issue thread, it discusses setting the port visibility to public, and I may have read somewhere about Google Cloud Shell Preview requiring account authentication to access the preview, so that could be the problem, although I am not sure.

To reproduce:
1. Launch Google Cloud Shell
2. `$ git clone https://github.com/titaniumnetwork-dev/Ultraviolet-App.git`
3. `$ cd Ultraviolet-App`
5. `$ npm install`
6. `$ npm start`
7. Open web preview
8. Go to any website

**Comment by ilikemen132** [comment]
L bozo

**Comment by tuta-amb** [comment]
> L bozo

What? Why is this L Bozo. That doesn't even make sense. If you are going to insult someone, at least try to think of something before just going like `L bozo ration skibidi toilet lmao`

**Comment by ProgrammerIn-wonderland** [comment]
This is because of how previews work on Google cloud shell, you'd have to modify UV to make this work

**Comment by Jokypond** [comment]
> > L bozo
> 
> What? Why is this L Bozo. That doesn't even make sense. If you are going to insult someone, at least try to think of something before just going like `L bozo ratio skill issue ohio amogus skibidi toilet lmao`. You probably spend half of your life skidding people's proxies and telling everyone how cool you are, you unblocked websites.

L bozo ratio skill issue ohio skibidi toilet lmao

**Comment by ProgrammerIn-wonderland** [comment]
Cut it out, both of you @Jokypond @ilikemen132

**Comment by Jokypond** [comment]
> Cut it out, both of you @Jokypond @ilikemen132

so sorry

**Comment by tuta-amb** [comment]
@ProgrammerIn-wonderland I'm not familiar with Ultraviolet internals, but if you could guide me in the right direction, I would be happy to make this on my own and submit a PR.

**Comment by ProgrammerIn-wonderland** [comment]
I'm honestly not sure where to start, it would also require understanding how Google cloud auth works, but you can give it a shot

**Comment by tuta-amb** [comment]
Alright, @ProgrammerIn-wonderland I'll give it a try. I'm assuming that becuase Google Cloud Shell Preview requires authentication, the service worker that proxies requests doesn't get the requests sent.

**Comment by xjzh123** [comment]
I have been installing Ultraviolet on Deta Space. The same problem encountered. I solved it by setting `public: true`, which I guess is basically the same as Gitpod's `set the port visibility to public`.
So I guess this happens because Ultraviolet's request to the bare server is blocked by authentication?

**Comment by proudparrot2** [comment]
Yeah pretty sure it has to do with a firewall issue

**Comment by tuta-amb** [comment]
@xjzh123 How are you running on Deta Space? Just curious. Is there an app from the marketplace available or do I need to create my own app? (Which is possible, since my dev mode request did get accepted)

**Comment by xjzh123** [comment]
> @xjzh123
> 
> > So I guess this happens because Ultraviolet's request to the bare server is blocked by authentication?
> 
> Definitely. This official Google article confirms it: [Cloud Shell - Preview web apps](https://cloud.google.com/shell/docs/using-web-preview#:~:text=These%20ports%20are%20only%20available%20to%20the%20secure%20Cloud%20Shell%20proxy%20service,%20which%20restricts%20access%20over%20HTTPS%20to%20your%20user%20account%20only.) I think this could be achieved if I found the authentication headers that are necessary to make requests to the preview backend, and sent them along in the service worker proxy.
> 
> Also: How are you running on Deta Space? Just curious. Is there an app from the marketplace available or do I need to create my own app? (Which is possible, since my dev mode request did get accepted)

I have created UltraViolet-App and Cobalt in the marketplace, so everyone can install them on deta.

**Comment by Riftriot** [comment]
Closed as stale
