### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by Typeist** [titaniumnetwork-dev/Ultraviolet#8]
How do you use middleware, I saw a commit saying it added a middleware system, but no documentation on how to use said system.

**Comment by e9x** [comment]
> How do you use middleware, I saw a commit saying it added a middleware system, but no documentation on how to use said system.

Middleware is built into the Ultraviolet objects that extend EventEmitter. You can look for hooks by finding events that are emitted:

https://github.com/titaniumnetwork-dev/Ultraviolet/search?q=.emit%28
