### ISSUE TITLE
No Discord support.

### ISSUE THREAD

**Issue by qFlox** [titaniumnetwork-dev/Ultraviolet#81]
I cant log into any websites through this, is this meant to happen?

**Comment by tuta-amb** [comment]
No.

**Comment by GavinGoGaming** [comment]
Discord does send a login-loop sometimes via QR code.

**Comment by qFlox** [comment]
nvm, its just not letting me login to any website

**Comment by Percslol** [comment]
incredibly stale issue, closing because no information was provided and seems to be inactive
