### ISSUE TITLE
The site give a 403 error when trying to go to spotify.com

### ISSUE THREAD

**Issue by XxHiroTTVxX** [titaniumnetwork-dev/Ultraviolet#9]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

It should just load up and work as the site says its supported in the git repo 

## Current Behavior

on search the site returns a 403 error and the pages dosen't load

## Possible Solution

I don't know any solution 

## Steps to Reproduce

1. go to any proxy that uses UV or my site https://weeb-central.icu
2. Search spotify.com
3. Get a 403 error
4. Thats all

**Comment by e9x** [comment]
This is due to Spotify blocking your Bare server's IP address.

**Comment by XxHiroTTVxX** [comment]
> This is due to Spotify blocking your Bare server's IP address.

hmmm so spotify is blocking TN's bare server Ip too ?

**Comment by e9x** [comment]
> hmmm so spotify is blocking TN's bare server Ip too ?

Yes.

**Comment by XxHiroTTVxX** [comment]
> > hmmm so spotify is blocking TN's bare server Ip too ?
> 
> Yes.

damn what can we do to fix this nothing?

**Comment by e9x** [comment]
> damn what can we do to fix this nothing?

Run your Bare server under a residential proxy or switch server IPs to evade IP bans.

**Comment by XxHiroTTVxX** [comment]
> Run your Bare server under a residential proxy or switch server IPs to evade IP bans.
Yea I'm not gonna do that spotify isn't that worth it lol
