### ISSUE TITLE
Broken now gg css

### ISSUE THREAD

**Issue by Harmomnykid** [titaniumnetwork-dev/Ultraviolet#90]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zkayns** [comment]
![35372b68f01c155d5a255a74829953db](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/80561998/9446896e-a152-40db-aa4a-783b83573552)

**Comment by Riftriot** [comment]
Closed as stale
