### ISSUE TITLE
Broken Now.GG CSS

### ISSUE THREAD

**Issue by VillainsRule** [titaniumnetwork-dev/Ultraviolet#91]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior
The site should display the styles on Now.GG.

## Current Behavior
The stylesheets are malformed/missing.

## Possible Solution
Unsure.

## Steps to Reproduce
1. Open Ultraviolet-App or any other UV based proxy.
2. Search for `now.gg` and open it.
3. Wait a few seconds, and watch the CSS fail.

## Context (Environment)
Original issue in [Interstellar](https://github.com/InterstellarNetwork/Interstellar/issues/307).

**Comment by IncognitoTGT** [comment]
it's not unmaintained

**Comment by IncognitoTGT** [comment]
they just don't have stuff to add rn 
<@1091735539025203220>
