### ISSUE TITLE
Discord.com usercards don't load.

### ISSUE THREAD

**Issue by Twofoursixeight2468** [titaniumnetwork-dev/Ultraviolet#92]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

The usercard loads correctly, with the profile details.

## Current Behavior

Profile details don't load.

## Possible Solution

Give more time to load the usercards

## Steps to Reproduce

1. Open discord on Ultraviolet
2. Click on a usercard
3. Usercard details are missing.

## Context (Environment)

This is a minor issue, but it interfers with reading profiles on discord.

## Detailed Description
When clicking on a usercard in discord using the proxy, the profile details, background, and badges are missing.
Attached bellow are the images of the issue.

What should happen:
![scrnli_12_7_2023_8-48-44 AM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/105664499/cbfa3d6f-01e1-411f-b896-e99bf70ad971)
What actually happens:
![scrnli_12_7_2023_8-47-56 AM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/105664499/3ef51934-55e5-44ea-8701-ff535e29d5ab)

## Possible Implementation

N/A

**Comment by tuta-amb** [comment]
Might be just you, usercards work fine for me on a home WiFi.

**Comment by Percslol** [comment]
could not reproduce this issue, also seems to be working for other users

closing because its stale and can't be reproduced
