### ISSUE TITLE
So what do i do next??

### ISSUE THREAD

**Issue by pretzer25** [titaniumnetwork-dev/Ultraviolet#93]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

I got my site deployed, but there is no index.html!?!?!?!?

## Expected Behavior

there should be a index.html file!!!

## Current Behavior

THERE IS NONE!!!

## Possible Solution

ADD ONE!!!

## Steps to Reproduce

DEPLOY SITE!!

## Context (Environment)

IT AFFECTED EVERYTHING!!!

## Detailed Description

NO INDEX.HTML

## Possible Implementation
NO

**Comment by zkayns** [comment]
![IMG-20220218-WA0005](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/80561998/389bc4ec-7f01-49c1-bc93-74079775c156)

**Comment by Riftriot** [comment]
How is it our problem if you didn't make HTML for your site

**Comment by ProgrammerIn-wonderland** [comment]
This is the repo for the service worker, if you want an easy deployment use ultraviolet-app

**Comment by IncognitoTGT** [comment]
@titaniumnetwork-dev/ultraviolet-app

**Comment by pretzer25** [comment]
ahhhh okay
