### ISSUE TITLE
Discord.com doesn't open

### ISSUE THREAD

**Issue by mala026** [titaniumnetwork-dev/Ultraviolet#96]
Discord doesn't load, i've restarted my device twice and it still sends me to the "error" page.

**Comment by proudparrot2** [comment]
can you provide an image

**Comment by mala026** [comment]
![Screenshot 2023-12-22 8 44 29 AM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/154618377/b29677ce-9b1a-4cf2-87d4-8540658ffd02)

**Comment by proudparrot2** [comment]
uhhh can you click on that bare server link and make sure its functioning correctly

**Comment by mala026** [comment]
clicked on it, this is what came up
![Screenshot 2023-12-22 8 49 32 AM](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/154618377/84867b3c-7989-4018-a858-36dc4feed6d4)

**Comment by proudparrot2** [comment]
Then your bare server isn't working. This most likely is not a problem with TN, as they don't host bares on hop

**Comment by mala026** [comment]
Oh okay, is there anything I can do to get it working again?

**Comment by tuta-amb** [comment]
@mala026 You would have to either host your own server or contact whoever owns the server.

**Comment by Riftriot** [comment]
Closed as stale
