### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Chenjiang-circle** [titaniumnetwork-dev/Ultraviolet#98]
when I successfully deployed Ultraviolet-App, I can access Youtube, Twitter etc., but when I access https://m.cn.nytimes.com/china, Ultraviolet return a error:
<img width="708" alt="image" src="https://github.com/titaniumnetwork-dev/Ultraviolet/assets/45083793/e3e7f476-e599-4361-b577-2e2019dbb04f">

**Comment by CoolElectronics** [comment]
the site has a bad cert. not a UV issue
