### ISSUE TITLE
RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

### ISSUE THREAD

**Issue by pretzer25** [titaniumnetwork-dev/Ultraviolet#99]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

to work

RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

umm... RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

fix it

1.try the proxy
2.
3.
4.

## Context (Environment)
verlcel

**Comment by tuta-amb** [comment]
Which proxy is this? This is generally caused by an invalid response from the proxy (bare) server.

**Comment by pretzer25** [comment]
https://ultraviolet-static-archive-sandy.vercel.app/

**Comment by tuta-amb** [comment]
@pretzner25 This is an issue with the bare server, it is not properly configured. Since you are deploying on Vercel, you cannot host the bare server (the proxy server) there, as it requires a backend (Vercel is a static host). You must either host a bare server somewhere else or use someone else's.
